
-- Update items 1-10: Threat Regulation
UPDATE bops_question_bank SET item_text = 'Student becomes defensive when corrected, even when the correction is delivered calmly.', linked_domain = 'threat', subscale = 'Response to gentle correction', reverse_scored = false, active = true WHERE item_number = 1;
UPDATE bops_question_bank SET item_text = 'Student assumes they are being blamed before the adult has finished speaking.', linked_domain = 'threat', subscale = 'Blame attribution before facts', reverse_scored = false, active = true WHERE item_number = 2;
UPDATE bops_question_bank SET item_text = 'Student watches adults closely for signs of frustration or disapproval, even when not the focus of attention.', linked_domain = 'threat', subscale = 'Adult monitoring and scanning', reverse_scored = false, active = true WHERE item_number = 3;
UPDATE bops_question_bank SET item_text = 'Student appears guarded, tense, or withdrawn when working with an unfamiliar adult.', linked_domain = 'threat', subscale = 'Unfamiliar staff response', reverse_scored = false, active = true WHERE item_number = 4;
UPDATE bops_question_bank SET item_text = 'Student shuts down or escalates more intensely when corrected in front of peers than when corrected privately.', linked_domain = 'threat', subscale = 'Public correction sensitivity', reverse_scored = false, active = true WHERE item_number = 5;
UPDATE bops_question_bank SET item_text = 'Student interprets neutral comments, tone, or facial expressions as signs of anger or disapproval.', linked_domain = 'threat', subscale = 'Neutral event misinterpretation', reverse_scored = false, active = true WHERE item_number = 6;
UPDATE bops_question_bank SET item_text = 'Student struggles to re-engage with an adult after a conflict, even after the adult has attempted to resolve it.', linked_domain = 'threat', subscale = 'Repair resistance after conflict', reverse_scored = false, active = true WHERE item_number = 7;
UPDATE bops_question_bank SET item_text = 'Student becomes visibly uncomfortable or tense when adults move close or lean in during instruction.', linked_domain = 'threat', subscale = 'Physical proximity discomfort', reverse_scored = false, active = true WHERE item_number = 8;
UPDATE bops_question_bank SET item_text = 'Student assumes peers are talking about them negatively or laughing at them without clear evidence.', linked_domain = 'threat', subscale = 'Peer blame attribution', reverse_scored = false, active = true WHERE item_number = 9;
UPDATE bops_question_bank SET item_text = 'Student defends themselves against criticism before any criticism has been given.', linked_domain = 'threat', subscale = 'Preemptive self-defense', reverse_scored = false, active = true WHERE item_number = 10;

-- Items 11-20: Withdrawal
UPDATE bops_question_bank SET item_text = 'Student moves away from or leaves group activities without explanation.', linked_domain = 'withdrawal', subscale = 'Physical group exit', reverse_scored = false, active = true WHERE item_number = 11;
UPDATE bops_question_bank SET item_text = 'Student struggles to join an already-established peer group, even when peers are welcoming.', linked_domain = 'withdrawal', subscale = 'Peer group entry difficulty', reverse_scored = false, active = true WHERE item_number = 12;
UPDATE bops_question_bank SET item_text = 'Student opts out of activities when expectations or outcomes are unclear.', linked_domain = 'withdrawal', subscale = 'Uncertainty-driven opt-out', reverse_scored = false, active = true WHERE item_number = 13;
UPDATE bops_question_bank SET item_text = 'Student chooses to work alone even when group participation is available and encouraged.', linked_domain = 'withdrawal', subscale = 'Consistent solo preference', reverse_scored = false, active = true WHERE item_number = 14;
UPDATE bops_question_bank SET item_text = 'Student watches peers participate from a distance rather than joining in.', linked_domain = 'withdrawal', subscale = 'Peripheral observation', reverse_scored = false, active = true WHERE item_number = 15;
UPDATE bops_question_bank SET item_text = 'Student declines or deflects when explicitly invited to participate by a peer or adult.', linked_domain = 'withdrawal', subscale = 'Declining direct invitations', reverse_scored = false, active = true WHERE item_number = 16;
UPDATE bops_question_bank SET item_text = 'Student withdraws from peers for an extended period after a social conflict or misunderstanding.', linked_domain = 'withdrawal', subscale = 'Post-conflict social retreat', reverse_scored = false, active = true WHERE item_number = 17;
UPDATE bops_question_bank SET item_text = 'Student avoids initiating contact with unfamiliar peers, even in structured settings.', linked_domain = 'withdrawal', subscale = 'New peer avoidance', reverse_scored = false, active = true WHERE item_number = 18;
UPDATE bops_question_bank SET item_text = 'Student becomes quiet and disengaged in group settings in a way that is easy to overlook.', linked_domain = 'withdrawal', subscale = 'Emotional invisibility', reverse_scored = false, active = true WHERE item_number = 19;
UPDATE bops_question_bank SET item_text = 'Student avoids seeking help or support from adults, even when struggling.', linked_domain = 'withdrawal', subscale = 'Adult connection avoidance', reverse_scored = false, active = true WHERE item_number = 20;

-- Items 21-31: Sensory (11 items)
UPDATE bops_question_bank SET item_text = 'Student reacts strongly to unexpected or incidental physical contact from peers or adults.', linked_domain = 'sensory', subscale = 'Unexpected touch reaction', reverse_scored = false, active = true WHERE item_number = 21;
UPDATE bops_question_bank SET item_text = 'Student becomes visibly overwhelmed or dysregulated in loud classroom or group settings.', linked_domain = 'sensory', subscale = 'Loud environment overwhelm', reverse_scored = false, active = true WHERE item_number = 22;
UPDATE bops_question_bank SET item_text = 'Student loses focus or becomes agitated in response to background noise that peers appear to ignore.', linked_domain = 'sensory', subscale = 'Background noise distraction', reverse_scored = false, active = true WHERE item_number = 23;
UPDATE bops_question_bank SET item_text = 'Student reacts with a strong startle response or visible distress to sudden loud sounds.', linked_domain = 'sensory', subscale = 'Sudden sound startle', reverse_scored = false, active = true WHERE item_number = 24;
UPDATE bops_question_bank SET item_text = 'Student avoids touching certain textures, materials, or objects used in classroom activities.', linked_domain = 'sensory', subscale = 'Tactile material avoidance', reverse_scored = false, active = true WHERE item_number = 25;
UPDATE bops_question_bank SET item_text = 'Student attempts to leave the area when the sensory environment becomes overwhelming.', linked_domain = 'sensory', subscale = 'Sensory-driven exit attempt', reverse_scored = false, active = true WHERE item_number = 26;
UPDATE bops_question_bank SET item_text = 'Student becomes dysregulated or agitated in crowded hallways, assemblies, or transitional spaces.', linked_domain = 'sensory', subscale = 'Crowded space dysregulation', reverse_scored = false, active = true WHERE item_number = 27;
UPDATE bops_question_bank SET item_text = 'Student struggles to focus in visually busy or cluttered environments.', linked_domain = 'sensory', subscale = 'Visual environment sensitivity', reverse_scored = false, active = true WHERE item_number = 28;
UPDATE bops_question_bank SET item_text = 'Student frequently complains about clothing, seating, or physical discomfort in ways that disrupt engagement.', linked_domain = 'sensory', subscale = 'Clothing or comfort complaints', reverse_scored = false, active = true WHERE item_number = 29;
UPDATE bops_question_bank SET item_text = 'Student escalates behaviorally after exposure to a sensory-heavy environment, even if the escalation occurs after the fact.', linked_domain = 'sensory', subscale = 'Sensory-triggered delayed escalation', reverse_scored = false, active = true WHERE item_number = 30;
UPDATE bops_question_bank SET item_text = 'Student shows strong negative reactions to smells or food-related sensory input in the classroom environment.', linked_domain = 'sensory', subscale = 'Smell or taste sensitivity', reverse_scored = false, active = true WHERE item_number = 31;

-- Items 32-42: Emotion (11 items)
UPDATE bops_question_bank SET item_text = 'Student stops engaging with a task entirely when they become frustrated, rather than asking for help or taking a break.', linked_domain = 'emotion', subscale = 'Frustration-driven shutdown', reverse_scored = false, active = true WHERE item_number = 32;
UPDATE bops_question_bank SET item_text = 'Student escalates from calm to visibly upset very quickly, with little warning.', linked_domain = 'emotion', subscale = 'Rapid escalation speed', reverse_scored = false, active = true WHERE item_number = 33;
UPDATE bops_question_bank SET item_text = 'Student takes a noticeably long time to calm down after becoming upset, even with adult support.', linked_domain = 'emotion', subscale = 'Extended recovery time', reverse_scored = false, active = true WHERE item_number = 34;
UPDATE bops_question_bank SET item_text = 'Student reacts with strong emotion to minor errors, small setbacks, or things not going as expected.', linked_domain = 'emotion', subscale = 'Small setback reactivity', reverse_scored = false, active = true WHERE item_number = 35;
UPDATE bops_question_bank SET item_text = 'Student remains emotionally dysregulated for an extended period after the triggering event has resolved.', linked_domain = 'emotion', subscale = 'Sustained post-trigger distress', reverse_scored = false, active = true WHERE item_number = 36;
UPDATE bops_question_bank SET item_text = 'Student displays emotional responses that appear much larger than what the situation would typically call for.', linked_domain = 'emotion', subscale = 'Disproportionate response intensity', reverse_scored = false, active = true WHERE item_number = 37;
UPDATE bops_question_bank SET item_text = 'Student gives up on a task at the first sign of difficulty, before making a sustained attempt.', linked_domain = 'emotion', subscale = 'First-difficulty abandonment', reverse_scored = false, active = true WHERE item_number = 38;
UPDATE bops_question_bank SET item_text = 'Student continues to escalate or remains upset even when an adult attempts to help them calm down.', linked_domain = 'emotion', subscale = 'Co-regulation resistance', reverse_scored = false, active = true WHERE item_number = 39;
UPDATE bops_question_bank SET item_text = 'Student expresses distress through outbursts — crying, yelling, or verbal expressions of strong emotion — in response to everyday frustrations.', linked_domain = 'emotion', subscale = 'Externalized emotional outburst', reverse_scored = false, active = true WHERE item_number = 40;
UPDATE bops_question_bank SET item_text = 'Student becomes upset in anticipation of a challenging task or situation, before it has actually begun.', linked_domain = 'emotion', subscale = 'Anticipatory distress', reverse_scored = false, active = true WHERE item_number = 41;
UPDATE bops_question_bank SET item_text = 'Student struggles to return to learning tasks after an emotional episode, even after appearing to calm down.', linked_domain = 'emotion', subscale = 'Difficulty re-engaging after upset', reverse_scored = false, active = true WHERE item_number = 42;

-- Items 43-52: Impulse
UPDATE bops_question_bank SET item_text = 'Student blurts out answers or comments during instruction without waiting to be called on.', linked_domain = 'impulse', subscale = 'Answer blurting', reverse_scored = false, active = true WHERE item_number = 43;
UPDATE bops_question_bank SET item_text = 'Student leaves their seat or workstation during instruction without permission.', linked_domain = 'impulse', subscale = 'Unsanctioned seat departure', reverse_scored = false, active = true WHERE item_number = 44;
UPDATE bops_question_bank SET item_text = 'Student interrupts peers during partner or group conversations.', linked_domain = 'impulse', subscale = 'Peer conversation interruption', reverse_scored = false, active = true WHERE item_number = 45;
UPDATE bops_question_bank SET item_text = 'Student interrupts adults during instruction or one-on-one conversations.', linked_domain = 'impulse', subscale = 'Adult conversation interruption', reverse_scored = false, active = true WHERE item_number = 46;
UPDATE bops_question_bank SET item_text = 'Student seeks constant movement — fidgeting, pacing, rocking, or moving around the room — during seated or quiet tasks.', linked_domain = 'impulse', subscale = 'Motor restlessness', reverse_scored = false, active = true WHERE item_number = 47;
UPDATE bops_question_bank SET item_text = 'Student acts before thinking through what will happen as a result.', linked_domain = 'impulse', subscale = 'Action before consequence', reverse_scored = false, active = true WHERE item_number = 48;
UPDATE bops_question_bank SET item_text = 'Student moves to the next activity or task before being directed to do so.', linked_domain = 'impulse', subscale = 'Premature activity transition', reverse_scored = false, active = true WHERE item_number = 49;
UPDATE bops_question_bank SET item_text = 'Student handles or picks up materials that are not intended for them without asking.', linked_domain = 'impulse', subscale = 'Unauthorized material handling', reverse_scored = false, active = true WHERE item_number = 50;
UPDATE bops_question_bank SET item_text = 'Student has difficulty waiting for their turn during games, discussions, or group activities.', linked_domain = 'impulse', subscale = 'Difficulty waiting turn', reverse_scored = false, active = true WHERE item_number = 51;
UPDATE bops_question_bank SET item_text = 'Student expresses regret or acknowledges a behavior was wrong immediately after it occurs, but repeats the same behavior shortly after.', linked_domain = 'impulse', subscale = 'Regret-without-change pattern', reverse_scored = false, active = true WHERE item_number = 52;

-- Items 53-62: Autonomy
UPDATE bops_question_bank SET item_text = 'Student attempts to negotiate or modify task requirements before beginning.', linked_domain = 'autonomy', subscale = 'Pre-task negotiation', reverse_scored = false, active = true WHERE item_number = 53;
UPDATE bops_question_bank SET item_text = 'Student disengages from non-preferred tasks but works productively on tasks they have chosen or find interesting.', linked_domain = 'autonomy', subscale = 'Selective engagement by preference', reverse_scored = false, active = true WHERE item_number = 54;
UPDATE bops_question_bank SET item_text = 'Student resists following multi-step directions when they perceive the steps as unnecessary.', linked_domain = 'autonomy', subscale = 'Perceived-unnecessary step resistance', reverse_scored = false, active = true WHERE item_number = 55;
UPDATE bops_question_bank SET item_text = 'Student insists on completing tasks their own way rather than following the given directions.', linked_domain = 'autonomy', subscale = 'Self-directed approach preference', reverse_scored = false, active = true WHERE item_number = 56;
UPDATE bops_question_bank SET item_text = 'Student refuses or dismisses adult assistance even when they are clearly struggling with a task.', linked_domain = 'autonomy', subscale = 'Help rejection when struggling', reverse_scored = false, active = true WHERE item_number = 57;
UPDATE bops_question_bank SET item_text = 'Student responds significantly more positively to directions framed as choices than to direct instructions.', linked_domain = 'autonomy', subscale = 'Choice-framing response', reverse_scored = false, active = true WHERE item_number = 58;
UPDATE bops_question_bank SET item_text = 'Student resists transitioning away from a preferred activity to a directed one, even with advance warning.', linked_domain = 'autonomy', subscale = 'Preferred activity transition resistance', reverse_scored = false, active = true WHERE item_number = 59;
UPDATE bops_question_bank SET item_text = 'Student proposes alternative approaches or solutions when given a direction they do not want to follow.', linked_domain = 'autonomy', subscale = 'Alternative solution offering', reverse_scored = false, active = true WHERE item_number = 60;
UPDATE bops_question_bank SET item_text = 'Student asks repeated clarifying questions about a task before beginning, even when directions are clear.', linked_domain = 'autonomy', subscale = 'Demand clarity seeking', reverse_scored = false, active = true WHERE item_number = 61;
UPDATE bops_question_bank SET item_text = 'Student demonstrates strong performance on tasks they chose or designed themselves, but produces noticeably less on assigned tasks.', linked_domain = 'autonomy', subscale = 'Competence-context inconsistency', reverse_scored = false, active = true WHERE item_number = 62;

-- Items 63-73: Authority (11 items)
UPDATE bops_question_bank SET item_text = 'Student refuses or ignores direct instructions from adults.', linked_domain = 'authority', subscale = 'Direct command refusal', reverse_scored = false, active = true WHERE item_number = 63;
UPDATE bops_question_bank SET item_text = 'Student argues with adults when corrected about behavior, even when the correction is accurate.', linked_domain = 'authority', subscale = 'Correction argument', reverse_scored = false, active = true WHERE item_number = 64;
UPDATE bops_question_bank SET item_text = 'Student openly questions or challenges rules in front of peers.', linked_domain = 'authority', subscale = 'Open rule challenge', reverse_scored = false, active = true WHERE item_number = 65;
UPDATE bops_question_bank SET item_text = 'Student''s behavior escalates or intensifies in response to disciplinary consequences.', linked_domain = 'authority', subscale = 'Discipline escalation', reverse_scored = false, active = true WHERE item_number = 66;
UPDATE bops_question_bank SET item_text = 'Student complies readily for some adults but consistently resists others, without a clear task-based reason.', linked_domain = 'authority', subscale = 'Adult selectivity', reverse_scored = false, active = true WHERE item_number = 67;
UPDATE bops_question_bank SET item_text = 'Student challenges authority more intensely when peers are watching than in one-on-one situations.', linked_domain = 'authority', subscale = 'Audience-amplified resistance', reverse_scored = false, active = true WHERE item_number = 68;
UPDATE bops_question_bank SET item_text = 'Student initially appears to comply with a direction but then escalates shortly after.', linked_domain = 'authority', subscale = 'Post-compliance escalation', reverse_scored = false, active = true WHERE item_number = 69;
UPDATE bops_question_bank SET item_text = 'Once in a conflict with an adult, student struggles to de-escalate even when given an opportunity to do so.', linked_domain = 'authority', subscale = 'Power struggle lock-in', reverse_scored = false, active = true WHERE item_number = 70;
UPDATE bops_question_bank SET item_text = 'Student responds to disciplinary actions — redirection, loss of privilege, office referral — with increased oppositional behavior.', linked_domain = 'authority', subscale = 'Negative discipline response', reverse_scored = false, active = true WHERE item_number = 71;
UPDATE bops_question_bank SET item_text = 'Student must have the last word in a conflict with an adult, even after the situation has been resolved.', linked_domain = 'authority', subscale = 'Last-word seeking', reverse_scored = false, active = true WHERE item_number = 72;
UPDATE bops_question_bank SET item_text = 'Student repeatedly tests the same rules or limits even after consequences have been applied.', linked_domain = 'authority', subscale = 'Limit-testing frequency', reverse_scored = false, active = true WHERE item_number = 73;

-- Items 74-83: Rigidity
UPDATE bops_question_bank SET item_text = 'Student becomes dysregulated when the daily routine changes without advance notice.', linked_domain = 'rigidity', subscale = 'Unannounced routine change', reverse_scored = false, active = true WHERE item_number = 74;
UPDATE bops_question_bank SET item_text = 'Student struggles with schedule or routine changes even when given advance warning.', linked_domain = 'rigidity', subscale = 'Announced schedule change', reverse_scored = false, active = true WHERE item_number = 75;
UPDATE bops_question_bank SET item_text = 'Student becomes upset when an established rule or classroom expectation changes.', linked_domain = 'rigidity', subscale = 'Rule or expectation change distress', reverse_scored = false, active = true WHERE item_number = 76;
UPDATE bops_question_bank SET item_text = 'Student has difficulty adapting when directions or expectations change partway through a task.', linked_domain = 'rigidity', subscale = 'Mid-task instruction change', reverse_scored = false, active = true WHERE item_number = 77;
UPDATE bops_question_bank SET item_text = 'Student insists there is only one correct way to complete a task and resists alternative approaches.', linked_domain = 'rigidity', subscale = 'Single correct method insistence', reverse_scored = false, active = true WHERE item_number = 78;
UPDATE bops_question_bank SET item_text = 'Student becomes distressed when a previously communicated plan does not happen as stated.', linked_domain = 'rigidity', subscale = 'Communicated plan deviation', reverse_scored = false, active = true WHERE item_number = 79;
UPDATE bops_question_bank SET item_text = 'Student needs to start a task over from the beginning after making a mistake, rather than correcting and continuing.', linked_domain = 'rigidity', subscale = 'Error restart compulsion', reverse_scored = false, active = true WHERE item_number = 80;
UPDATE bops_question_bank SET item_text = 'Student has significant difficulty with transitions between activities, particularly when the next activity is not known in advance.', linked_domain = 'rigidity', subscale = 'Transition difficulty', reverse_scored = false, active = true WHERE item_number = 81;
UPDATE bops_question_bank SET item_text = 'Student becomes upset when an expected person, material, or activity is substituted without explanation.', linked_domain = 'rigidity', subscale = 'Unexpected substitution distress', reverse_scored = false, active = true WHERE item_number = 82;
UPDATE bops_question_bank SET item_text = 'Student has difficulty letting go of a previous event or conflict and returns to it repeatedly throughout the day.', linked_domain = 'rigidity', subscale = 'Perseveration on past events', reverse_scored = false, active = true WHERE item_number = 83;

-- Items 84-93: Social
UPDATE bops_question_bank SET item_text = 'Student misinterprets accidental peer actions — bumping into them, not responding — as intentional or hostile.', linked_domain = 'social', subscale = 'Peer intention misread', reverse_scored = false, active = true WHERE item_number = 84;
UPDATE bops_question_bank SET item_text = 'Student misses or misreads nonverbal cues from peers, such as body language or facial expressions.', linked_domain = 'social', subscale = 'Nonverbal cue reading', reverse_scored = false, active = true WHERE item_number = 85;
UPDATE bops_question_bank SET item_text = 'Student appears confused by the unspoken social rules that peer groups follow.', linked_domain = 'social', subscale = 'Unwritten peer group rules', reverse_scored = false, active = true WHERE item_number = 86;
UPDATE bops_question_bank SET item_text = 'Student struggles to tell when peers are joking, being sarcastic, or being serious.', linked_domain = 'social', subscale = 'Tone and sarcasm reading', reverse_scored = false, active = true WHERE item_number = 87;
UPDATE bops_question_bank SET item_text = 'Student has difficulty accurately reading the emotional expressions of peers, leading to mismatched responses.', linked_domain = 'social', subscale = 'Facial expression reading', reverse_scored = false, active = true WHERE item_number = 88;
UPDATE bops_question_bank SET item_text = 'Student does not reliably pick up on signals that it is another person''s turn to speak.', linked_domain = 'social', subscale = 'Conversational turn-taking', reverse_scored = false, active = true WHERE item_number = 89;
UPDATE bops_question_bank SET item_text = 'Student appears unaware of social hierarchies, shifting alliances, or status changes within the peer group.', linked_domain = 'social', subscale = 'Peer status and group dynamics', reverse_scored = false, active = true WHERE item_number = 90;
UPDATE bops_question_bank SET item_text = 'Student initiates conflicts with peers based on a misunderstanding of what the peer said or intended.', linked_domain = 'social', subscale = 'Misread-driven conflict', reverse_scored = false, active = true WHERE item_number = 91;
UPDATE bops_question_bank SET item_text = 'Student makes social repair attempts that land awkwardly or escalate rather than resolve peer conflicts.', linked_domain = 'social', subscale = 'Awkward social repair attempts', reverse_scored = false, active = true WHERE item_number = 92;
UPDATE bops_question_bank SET item_text = 'Student interprets peer situations — a group not making room, peers talking quietly — as deliberate exclusion when it may not be.', linked_domain = 'social', subscale = 'Exclusion vs. coincidence reading', reverse_scored = false, active = true WHERE item_number = 93;

-- Items 94-104: Context (11 items)
UPDATE bops_question_bank SET item_text = 'Student''s behavior is noticeably better or worse depending on which teacher is present.', linked_domain = 'context', subscale = 'Teacher-dependent behavior', reverse_scored = false, active = true WHERE item_number = 94;
UPDATE bops_question_bank SET item_text = 'Student shows significantly different behavior across different academic subjects.', linked_domain = 'context', subscale = 'Subject-dependent behavior', reverse_scored = false, active = true WHERE item_number = 95;
UPDATE bops_question_bank SET item_text = 'Student behaves noticeably differently in different classroom settings, even with the same expectations.', linked_domain = 'context', subscale = 'Classroom environment variation', reverse_scored = false, active = true WHERE item_number = 96;
UPDATE bops_question_bank SET item_text = 'Student''s behavior changes significantly depending on which peers are present.', linked_domain = 'context', subscale = 'Peer configuration effect', reverse_scored = false, active = true WHERE item_number = 97;
UPDATE bops_question_bank SET item_text = 'Student functions noticeably better in highly structured settings but struggles when expectations are less defined, or vice versa.', linked_domain = 'context', subscale = 'Structured vs. unstructured contrast', reverse_scored = false, active = true WHERE item_number = 98;
UPDATE bops_question_bank SET item_text = 'Student''s behavioral and academic performance is noticeably stronger with preferred adults than with others.', linked_domain = 'context', subscale = 'Preferred vs. non-preferred adult', reverse_scored = false, active = true WHERE item_number = 99;
UPDATE bops_question_bank SET item_text = 'Student''s behavior shifts predictably at specific points in the school day — mornings, after lunch, or at the end of day.', linked_domain = 'context', subscale = 'Time-of-day pattern', reverse_scored = false, active = true WHERE item_number = 100;
UPDATE bops_question_bank SET item_text = 'Student''s behavior improves noticeably when being directly observed or evaluated, and deteriorates when observation is removed.', linked_domain = 'context', subscale = 'Observation effect', reverse_scored = false, active = true WHERE item_number = 101;
UPDATE bops_question_bank SET item_text = 'There is a significant discrepancy between how the student''s behavior is described at home versus at school.', linked_domain = 'context', subscale = 'Home-to-school discrepancy', reverse_scored = false, active = true WHERE item_number = 102;
UPDATE bops_question_bank SET item_text = 'Student behaves differently when working one-on-one with a paraprofessional versus in the general classroom setting.', linked_domain = 'context', subscale = 'Para vs. teacher contrast', reverse_scored = false, active = true WHERE item_number = 103;
UPDATE bops_question_bank SET item_text = 'Different adults who work with this student describe their behavior in ways that seem inconsistent or contradictory.', linked_domain = 'context', subscale = 'Rater disagreement', reverse_scored = false, active = true WHERE item_number = 104;

-- Deactivate items 105-136 (no longer part of the instrument)
UPDATE bops_question_bank SET active = false WHERE item_number > 104;
