-- Batch 12: 504, Medical, Chronic Illness & Anxiety Supports (Items 166-180)
INSERT INTO public.iep_library_items (item_type, title, description, implementation_notes, domains, disability_tags, grade_band, setting_tags, topics, contraindications, idea_compliance_level, export_language, status)
VALUES
  ('accommodation', '504 Health Accommodation Plan', 'Implementation of accommodations aligned with a Section 504 health plan.', '["Coordinate with nurse and administration", "Review plan annually or as needed"]'::jsonb, ARRAY['health_medical'], ARRAY['other_health_impairment', '504_only'], ARRAY['preschool', 'elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['504_plan'], ARRAY[]::text[], 'safe', '{"iep": "Implementation of accommodations aligned with a Section 504 health plan.", "parent": "The school will follow your child''s 504 health accommodations."}'::jsonb, 'active'),
  ('accommodation', 'Flexible Attendance for Chronic Illness', 'Attendance expectations are adjusted due to chronic medical conditions.', '["Require medical documentation", "Provide make-up access to instruction"]'::jsonb, ARRAY['attendance', 'health_medical'], ARRAY['other_health_impairment', '504_only'], ARRAY['elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['chronic_illness'], ARRAY[]::text[], 'safe', '{"iep": "Attendance flexibility provided due to chronic medical needs.", "parent": "Attendance may be adjusted when your child is not feeling well."}'::jsonb, 'active'),
  ('accommodation', 'Medical Appointment Excused Absences', 'Absences for medical appointments are excused without penalty.', '["Coordinate documentation procedures", "Ensure access to missed work"]'::jsonb, ARRAY['attendance'], ARRAY['other_health_impairment', '504_only'], ARRAY['preschool', 'elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['medical_access'], ARRAY[]::text[], 'safe', '{"iep": "Medical appointment absences excused without academic penalty.", "parent": "Medical appointments will not negatively impact attendance."}'::jsonb, 'active'),
  ('accommodation', 'Modified Physical Expectations During Illness', 'Physical activity expectations are adjusted during illness or fatigue.', '["Communicate daily health status", "Adjust PE or movement demands"]'::jsonb, ARRAY['motor_physical', 'health_medical'], ARRAY['other_health_impairment', '504_only'], ARRAY['preschool', 'elementary', 'middle_school', 'high_school'], ARRAY['pe'], ARRAY['fatigue_management'], ARRAY[]::text[], 'safe', '{"iep": "Adjusted physical activity expectations during illness or fatigue.", "parent": "Your child''s physical activity may be reduced when needed."}'::jsonb, 'active'),
  ('accommodation', 'Testing Flexibility Due to Medical Needs', 'Testing schedules are adjusted when medical symptoms interfere with performance.', '["Allow rescheduling", "Avoid penalizing health-related absences"]'::jsonb, ARRAY['testing_assessment'], ARRAY['other_health_impairment', '504_only'], ARRAY['middle_school', 'high_school'], ARRAY['testing'], ARRAY['assessment_access'], ARRAY[]::text[], 'safe', '{"iep": "Testing schedules adjusted to accommodate medical needs.", "parent": "Tests may be rescheduled if health interferes."}'::jsonb, 'active'),
  ('accommodation', 'Anxiety-Informed Attendance Support', 'Attendance supports consider anxiety-related barriers to school participation.', '["Coordinate with counseling staff", "Use gradual return plans when needed"]'::jsonb, ARRAY['attendance', 'mental_health'], ARRAY['anxiety'], ARRAY['elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['school_refusal'], ARRAY['Avoid punitive attendance responses'], 'safe', '{"iep": "Attendance supports provided with consideration of anxiety.", "parent": "The school will support attendance when anxiety is a factor."}'::jsonb, 'active'),
  ('accommodation', 'Safe Space Access for Anxiety Episodes', 'Student may access a designated space during acute anxiety episodes.', '["Ensure supervision", "Pair with coping strategy instruction"]'::jsonb, ARRAY['mental_health'], ARRAY['anxiety'], ARRAY['elementary', 'middle_school'], ARRAY['general_ed'], ARRAY['panic_support'], ARRAY[]::text[], 'caution', '{"iep": "Access to a designated space during anxiety episodes.", "parent": "Your child may go to a safe space when feeling overwhelmed."}'::jsonb, 'active'),
  ('accommodation', 'Modified Homework Expectations During Illness', 'Homework expectations are adjusted during periods of illness.', '["Prioritize essential work", "Allow extensions without penalty"]'::jsonb, ARRAY['academics', 'health_medical'], ARRAY['other_health_impairment', '504_only'], ARRAY['preschool', 'elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['workload_management'], ARRAY[]::text[], 'safe', '{"iep": "Homework expectations adjusted during illness.", "parent": "Homework may be reduced when your child is not well."}'::jsonb, 'active'),
  ('accommodation', 'Health Condition Confidentiality Protections', 'Student health information is handled confidentially.', '["Limit access to necessary staff", "Follow FERPA and HIPAA guidance"]'::jsonb, ARRAY['health_medical'], ARRAY['504_only'], ARRAY['preschool', 'elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['confidentiality'], ARRAY[]::text[], 'safe', '{"iep": "Health information handled confidentially per policy.", "parent": "Your child''s health information will be kept private."}'::jsonb, 'active'),
  ('accommodation', 'Health-Related Schedule Adjustments', 'Daily schedule adjusted to accommodate stamina or treatment needs.', '["Coordinate with caregivers", "Review impact regularly"]'::jsonb, ARRAY['health_medical'], ARRAY['other_health_impairment', '504_only'], ARRAY['middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['schedule_flexibility'], ARRAY[]::text[], 'safe', '{"iep": "Schedule adjustments provided due to health needs.", "parent": "Your child''s schedule may be adjusted for health reasons."}'::jsonb, 'active'),
  ('accommodation', 'Temporary Remote Instruction Option', 'Remote instruction is provided during extended medical absences when feasible.', '["Align with district policy", "Ensure instructional access"]'::jsonb, ARRAY['attendance', 'academics'], ARRAY['other_health_impairment'], ARRAY['middle_school', 'high_school'], ARRAY['remote_learning'], ARRAY['medical_absence'], ARRAY['Subject to district approval'], 'caution', '{"iep": "Temporary remote instruction during extended medical absences.", "parent": "Your child may receive instruction from home when medically necessary."}'::jsonb, 'active'),
  ('accommodation', 'Anxiety-Informed Testing Environment', 'Testing conditions adjusted to reduce anxiety-related barriers.', '["Provide small group or quiet setting", "Allow breaks"]'::jsonb, ARRAY['testing_assessment', 'mental_health'], ARRAY['anxiety'], ARRAY['elementary', 'middle_school', 'high_school'], ARRAY['testing'], ARRAY['test_anxiety'], ARRAY[]::text[], 'safe', '{"iep": "Testing environment adjusted to reduce anxiety.", "parent": "Your child may test in a quieter or less stressful setting."}'::jsonb, 'active'),
  ('accommodation', 'Modified Participation Expectations During Flare-Ups', 'Participation expectations adjusted during medical symptom flare-ups.', '["Communicate symptom status", "Prioritize core participation"]'::jsonb, ARRAY['academics', 'health_medical'], ARRAY['other_health_impairment'], ARRAY['preschool', 'elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['flare_management'], ARRAY[]::text[], 'safe', '{"iep": "Participation expectations adjusted during health flare-ups.", "parent": "Your child may be excused from some activities when symptoms flare."}'::jsonb, 'active'),
  ('accommodation', 'Staff Awareness of Medical Triggers', 'Relevant staff are informed of medical or anxiety triggers.', '["Share on a need-to-know basis", "Review triggers periodically"]'::jsonb, ARRAY['health_medical', 'mental_health'], ARRAY['other_health_impairment', 'anxiety'], ARRAY['preschool', 'elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['trigger_management'], ARRAY[]::text[], 'safe', '{"iep": "Staff informed of medical or anxiety-related triggers.", "parent": "Teachers will know what may affect your child''s health or anxiety."}'::jsonb, 'active'),
  ('accommodation', 'Health-Based Re-Entry Planning', 'Support provided for re-entry after extended medical absence.', '["Gradual return schedule", "Coordinate with counseling and academics"]'::jsonb, ARRAY['attendance', 'health_medical'], ARRAY['other_health_impairment'], ARRAY['preschool', 'elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['reentry_support'], ARRAY[]::text[], 'safe', '{"iep": "Re-entry planning provided following medical absence.", "parent": "The school will support your child''s return after being out sick."}'::jsonb, 'active');

-- Batch 13: Teacher Implementation & Classroom Systems (Items 181-195)
INSERT INTO public.iep_library_items (item_type, title, description, implementation_notes, domains, disability_tags, grade_band, setting_tags, topics, contraindications, idea_compliance_level, export_language, status)
VALUES
  ('accommodation', 'IEP Fidelity Checklist', 'Teachers use a checklist to ensure IEP accommodations are implemented consistently.', '["Review checklist weekly", "Document barriers and supports"]'::jsonb, ARRAY['implementation'], ARRAY['autism', 'adhd', 'specific_learning_disability', 'other_health_impairment'], ARRAY['preschool', 'elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['fidelity'], ARRAY[]::text[], 'safe', '{"iep": "Use of an IEP fidelity checklist to support consistent implementation.", "parent": "Teachers will track that accommodations are being used."}'::jsonb, 'active'),
  ('accommodation', 'IEP Accommodation Quick-Reference Sheet', 'A one-page summary of accommodations is available to staff.', '["Keep accessible but confidential", "Update after meetings"]'::jsonb, ARRAY['implementation'], ARRAY['autism', 'adhd', 'specific_learning_disability', 'other_health_impairment'], ARRAY['preschool', 'elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['staff_support'], ARRAY[]::text[], 'safe', '{"iep": "Quick-reference summary of accommodations provided to staff.", "parent": "Teachers will have a summary of your child''s supports."}'::jsonb, 'active'),
  ('accommodation', 'Cross-Staff Communication Protocol', 'Procedures ensure consistent communication among staff working with the student.', '["Identify primary point of contact", "Schedule regular updates"]'::jsonb, ARRAY['implementation'], ARRAY['autism', 'adhd', 'specific_learning_disability', 'other_health_impairment'], ARRAY['preschool', 'elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['communication'], ARRAY[]::text[], 'safe', '{"iep": "Communication protocols established among staff.", "parent": "Staff will communicate to stay aligned on supports."}'::jsonb, 'active'),
  ('accommodation', 'Substitute Teacher Accommodation Plan', 'Accommodation information is accessible to substitute teachers.', '["Provide simplified guidance", "Maintain confidentiality"]'::jsonb, ARRAY['implementation'], ARRAY['autism', 'adhd', 'specific_learning_disability', 'other_health_impairment'], ARRAY['preschool', 'elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['sub_support'], ARRAY[]::text[], 'safe', '{"iep": "Accommodation guidance available for substitute teachers.", "parent": "Substitute teachers will know how to support your child."}'::jsonb, 'active'),
  ('accommodation', 'Documentation of Accommodation Use', 'Staff document when accommodations are provided.', '["Use simple tracking method", "Review documentation periodically"]'::jsonb, ARRAY['implementation'], ARRAY['autism', 'adhd', 'specific_learning_disability', 'other_health_impairment'], ARRAY['preschool', 'elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['documentation'], ARRAY[]::text[], 'safe', '{"iep": "Documentation of accommodation implementation maintained.", "parent": "The school will track when supports are used."}'::jsonb, 'active'),
  ('accommodation', 'Teacher Training on Disability Awareness', 'Teachers receive training related to disability-specific needs.', '["Provide ongoing professional development", "Include practical strategies"]'::jsonb, ARRAY['implementation'], ARRAY['autism', 'adhd', 'specific_learning_disability', 'other_health_impairment'], ARRAY['preschool', 'elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['professional_development'], ARRAY[]::text[], 'safe', '{"iep": "Teacher training provided on disability-related needs.", "parent": "Teachers will be trained on how to support your child."}'::jsonb, 'active'),
  ('accommodation', 'Classroom Accommodation Audits', 'Periodic reviews ensure accommodations are available and effective.', '["Conduct audits quarterly", "Address gaps promptly"]'::jsonb, ARRAY['implementation'], ARRAY['autism', 'adhd', 'specific_learning_disability', 'other_health_impairment'], ARRAY['preschool', 'elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['quality_control'], ARRAY[]::text[], 'safe', '{"iep": "Periodic classroom accommodation audits conducted.", "parent": "The school will review whether supports are working."}'::jsonb, 'active'),
  ('accommodation', 'Staff Access to Behavior and Support Plans', 'Relevant staff can access behavior and support plans as needed.', '["Maintain secure access", "Review plans regularly"]'::jsonb, ARRAY['implementation', 'behavior'], ARRAY['autism', 'adhd', 'emotional_disturbance'], ARRAY['preschool', 'elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['plan_access'], ARRAY[]::text[], 'safe', '{"iep": "Staff access to behavior and support plans ensured.", "parent": "Staff will know how to support your child''s behavior."}'::jsonb, 'active'),
  ('accommodation', 'Implementation Feedback Loop', 'Teachers provide feedback on accommodation effectiveness.', '["Collect feedback regularly", "Adjust supports as needed"]'::jsonb, ARRAY['implementation'], ARRAY['autism', 'adhd', 'specific_learning_disability', 'other_health_impairment'], ARRAY['preschool', 'elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['continuous_improvement'], ARRAY[]::text[], 'safe', '{"iep": "Feedback process in place to refine accommodations.", "parent": "The school will adjust supports based on what works."}'::jsonb, 'active'),
  ('accommodation', 'IEP Meeting Follow-Up Summary', 'Staff receive a summary of decisions following IEP meetings.', '["Distribute promptly", "Highlight changes"]'::jsonb, ARRAY['implementation'], ARRAY['autism', 'adhd', 'specific_learning_disability', 'other_health_impairment'], ARRAY['preschool', 'elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['meeting_followup'], ARRAY[]::text[], 'safe', '{"iep": "Post-meeting summaries shared with staff.", "parent": "Teachers will be informed of IEP updates."}'::jsonb, 'active'),
  ('accommodation', 'Consistency Across Classrooms', 'Accommodations implemented consistently across settings.', '["Align staff expectations", "Monitor consistency"]'::jsonb, ARRAY['implementation'], ARRAY['autism', 'adhd', 'specific_learning_disability', 'other_health_impairment'], ARRAY['preschool', 'elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['consistency'], ARRAY[]::text[], 'safe', '{"iep": "Consistency ensured across classrooms.", "parent": "Your child''s supports will be consistent."}'::jsonb, 'active'),
  ('accommodation', 'Data Review for Accommodation Effectiveness', 'Data is reviewed to determine whether accommodations are effective.', '["Use academic and behavioral data", "Adjust supports based on findings"]'::jsonb, ARRAY['implementation'], ARRAY['autism', 'adhd', 'specific_learning_disability', 'other_health_impairment'], ARRAY['preschool', 'elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['data_based_decisions'], ARRAY[]::text[], 'safe', '{"iep": "Data reviewed to evaluate accommodation effectiveness.", "parent": "The school will look at data to see if supports are helping."}'::jsonb, 'active'),
  ('accommodation', 'Accommodation Revision Protocol', 'Clear process exists for revising accommodations when needed.', '["Document changes", "Notify team members"]'::jsonb, ARRAY['implementation'], ARRAY['autism', 'adhd', 'specific_learning_disability', 'other_health_impairment'], ARRAY['preschool', 'elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['revision_process'], ARRAY[]::text[], 'safe', '{"iep": "Process established for revising accommodations.", "parent": "Supports may be updated if needs change."}'::jsonb, 'active'),
  ('accommodation', 'Family Communication on Implementation', 'Families receive updates on accommodation implementation.', '["Communicate regularly", "Share progress and concerns"]'::jsonb, ARRAY['implementation'], ARRAY['autism', 'adhd', 'specific_learning_disability', 'other_health_impairment'], ARRAY['preschool', 'elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['family_communication'], ARRAY[]::text[], 'safe', '{"iep": "Family communication maintained regarding accommodation use.", "parent": "You will receive updates about how supports are used."}'::jsonb, 'active'),
  ('accommodation', 'Implementation Transition Between School Years', 'Accommodation continuity ensured during grade or school transitions.', '["Share information with receiving staff", "Review supports at start of year"]'::jsonb, ARRAY['implementation', 'transitions'], ARRAY['autism', 'adhd', 'specific_learning_disability', 'other_health_impairment'], ARRAY['preschool', 'elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['year_transition'], ARRAY[]::text[], 'safe', '{"iep": "Continuity of accommodations ensured between school years.", "parent": "Supports will carry over into the next school year."}'::jsonb, 'active');

-- Batch 14: District-Safe Compliance & Administrative Supports (FINAL) (Items 196-210)
INSERT INTO public.iep_library_items (item_type, title, description, implementation_notes, domains, disability_tags, grade_band, setting_tags, topics, contraindications, idea_compliance_level, export_language, status)
VALUES
  ('accommodation', 'IDEA Compliance Review', 'IEP accommodations reviewed to ensure IDEA compliance.', '["Conduct annual reviews", "Address noncompliance promptly"]'::jsonb, ARRAY['compliance'], ARRAY['autism', 'adhd', 'specific_learning_disability', 'other_health_impairment', 'intellectual_disability'], ARRAY['preschool', 'elementary', 'middle_school', 'high_school'], ARRAY['administration'], ARRAY['idea_compliance'], ARRAY[]::text[], 'safe', '{"iep": "Regular review conducted to ensure IDEA compliance.", "parent": "The school will ensure your child''s IEP meets legal requirements."}'::jsonb, 'active'),
  ('accommodation', '504 Compliance Monitoring', 'Section 504 accommodations monitored for compliance.', '["Review annually", "Document implementation"]'::jsonb, ARRAY['compliance'], ARRAY['504_only'], ARRAY['preschool', 'elementary', 'middle_school', 'high_school'], ARRAY['administration'], ARRAY['504_compliance'], ARRAY[]::text[], 'safe', '{"iep": "Monitoring of 504 accommodations for compliance.", "parent": "The school will ensure your child''s 504 plan is followed."}'::jsonb, 'active'),
  ('accommodation', 'Least Restrictive Environment (LRE) Review', 'Placement reviewed to ensure education in the least restrictive environment.', '["Review placement data", "Document justification"]'::jsonb, ARRAY['compliance'], ARRAY['autism', 'adhd', 'specific_learning_disability', 'other_health_impairment', 'intellectual_disability'], ARRAY['preschool', 'elementary', 'middle_school', 'high_school'], ARRAY['administration'], ARRAY['lre'], ARRAY[]::text[], 'safe', '{"iep": "Review conducted to ensure placement in the least restrictive environment.", "parent": "The school will review whether your child is learning in the right setting."}'::jsonb, 'active'),
  ('accommodation', 'Procedural Safeguards Distribution', 'Families receive procedural safeguards information.', '["Provide annually or when required", "Document receipt"]'::jsonb, ARRAY['compliance'], ARRAY['autism', 'adhd', 'specific_learning_disability', 'other_health_impairment', 'intellectual_disability'], ARRAY['preschool', 'elementary', 'middle_school', 'high_school'], ARRAY['administration'], ARRAY['procedural_safeguards'], ARRAY[]::text[], 'safe', '{"iep": "Procedural safeguards provided to families.", "parent": "You will receive information about your rights."}'::jsonb, 'active'),
  ('accommodation', 'Documentation Retention Protocol', 'IEP and 504 documentation retained per legal requirements.', '["Follow district timelines", "Ensure secure storage"]'::jsonb, ARRAY['compliance'], ARRAY['autism', 'adhd', 'specific_learning_disability', 'other_health_impairment', 'intellectual_disability', '504_only'], ARRAY['preschool', 'elementary', 'middle_school', 'high_school'], ARRAY['administration'], ARRAY['recordkeeping'], ARRAY[]::text[], 'safe', '{"iep": "Documentation retained per legal requirements.", "parent": "Your child''s records will be stored securely."}'::jsonb, 'active'),
  ('accommodation', 'Prior Written Notice Procedures', 'Changes to services documented using prior written notice.', '["Issue promptly", "Explain rationale clearly"]'::jsonb, ARRAY['compliance'], ARRAY['autism', 'adhd', 'specific_learning_disability', 'other_health_impairment', 'intellectual_disability'], ARRAY['preschool', 'elementary', 'middle_school', 'high_school'], ARRAY['administration'], ARRAY['pwn'], ARRAY[]::text[], 'safe', '{"iep": "Prior written notice issued for service changes.", "parent": "You will be notified in writing about changes."}'::jsonb, 'active'),
  ('accommodation', 'Due Process Awareness', 'Staff ensure families are informed of dispute resolution options.', '["Share resources", "Document communication"]'::jsonb, ARRAY['compliance'], ARRAY['autism', 'adhd', 'specific_learning_disability', 'other_health_impairment', 'intellectual_disability'], ARRAY['preschool', 'elementary', 'middle_school', 'high_school'], ARRAY['administration'], ARRAY['due_process'], ARRAY[]::text[], 'safe', '{"iep": "Families informed of due process options.", "parent": "You will be told how to resolve disagreements if needed."}'::jsonb, 'active'),
  ('accommodation', 'IEP Amendment Protocol', 'Clear procedures exist for amending IEPs between annual meetings.', '["Document amendments", "Obtain required consent"]'::jsonb, ARRAY['compliance'], ARRAY['autism', 'adhd', 'specific_learning_disability', 'other_health_impairment', 'intellectual_disability'], ARRAY['preschool', 'elementary', 'middle_school', 'high_school'], ARRAY['administration'], ARRAY['iep_amendment'], ARRAY[]::text[], 'safe', '{"iep": "Procedures established for IEP amendments.", "parent": "IEPs can be updated without waiting for the annual meeting."}'::jsonb, 'active'),
  ('accommodation', 'Consent Documentation Procedures', 'Parental consent documented for evaluations and services.', '["Use approved forms", "Maintain records"]'::jsonb, ARRAY['compliance'], ARRAY['autism', 'adhd', 'specific_learning_disability', 'other_health_impairment', 'intellectual_disability'], ARRAY['preschool', 'elementary', 'middle_school', 'high_school'], ARRAY['administration'], ARRAY['parental_consent'], ARRAY[]::text[], 'safe', '{"iep": "Parental consent documented for evaluations and services.", "parent": "The school will document your consent."}'::jsonb, 'active'),
  ('accommodation', 'Evaluation Timelines Monitoring', 'Evaluation timelines tracked to ensure legal compliance.', '["Monitor deadlines", "Notify team of delays"]'::jsonb, ARRAY['compliance'], ARRAY['autism', 'adhd', 'specific_learning_disability', 'other_health_impairment', 'intellectual_disability'], ARRAY['preschool', 'elementary', 'middle_school', 'high_school'], ARRAY['administration'], ARRAY['evaluation_timelines'], ARRAY[]::text[], 'safe', '{"iep": "Evaluation timelines monitored for compliance.", "parent": "The school will complete evaluations on time."}'::jsonb, 'active'),
  ('accommodation', 'Service Minutes Tracking', 'Related service minutes tracked to ensure delivery as written.', '["Review logs regularly", "Address missed minutes"]'::jsonb, ARRAY['compliance'], ARRAY['autism', 'adhd', 'specific_learning_disability', 'other_health_impairment', 'intellectual_disability'], ARRAY['preschool', 'elementary', 'middle_school', 'high_school'], ARRAY['administration'], ARRAY['service_delivery'], ARRAY[]::text[], 'safe', '{"iep": "Service minutes tracked to ensure delivery.", "parent": "The school will ensure services are provided as planned."}'::jsonb, 'active'),
  ('accommodation', 'Progress Reporting Compliance', 'IEP progress reports provided according to schedule.', '["Align with reporting periods", "Use clear language"]'::jsonb, ARRAY['compliance'], ARRAY['autism', 'adhd', 'specific_learning_disability', 'other_health_impairment', 'intellectual_disability'], ARRAY['preschool', 'elementary', 'middle_school', 'high_school'], ARRAY['administration'], ARRAY['progress_reporting'], ARRAY[]::text[], 'safe', '{"iep": "Progress reports provided per schedule.", "parent": "You will receive updates on progress."}'::jsonb, 'active'),
  ('accommodation', 'IEP Meeting Scheduling Compliance', 'IEP meetings scheduled within required timelines.', '["Provide adequate notice", "Document attempts"]'::jsonb, ARRAY['compliance'], ARRAY['autism', 'adhd', 'specific_learning_disability', 'other_health_impairment', 'intellectual_disability'], ARRAY['preschool', 'elementary', 'middle_school', 'high_school'], ARRAY['administration'], ARRAY['meeting_timeline'], ARRAY[]::text[], 'safe', '{"iep": "IEP meetings scheduled in compliance with timelines.", "parent": "Meetings will be scheduled on time."}'::jsonb, 'active'),
  ('accommodation', 'District Policy Alignment Review', 'IEP practices reviewed for alignment with district policy.', '["Review annually", "Update procedures as needed"]'::jsonb, ARRAY['compliance'], ARRAY['autism', 'adhd', 'specific_learning_disability', 'other_health_impairment', 'intellectual_disability'], ARRAY['preschool', 'elementary', 'middle_school', 'high_school'], ARRAY['administration'], ARRAY['policy_alignment'], ARRAY[]::text[], 'safe', '{"iep": "IEP practices aligned with district policy.", "parent": "The school will follow district rules."}'::jsonb, 'active'),
  ('accommodation', 'Compliance Audit Preparedness', 'School maintains readiness for compliance audits.', '["Maintain documentation", "Train staff on procedures"]'::jsonb, ARRAY['compliance'], ARRAY['autism', 'adhd', 'specific_learning_disability', 'other_health_impairment', 'intellectual_disability', '504_only'], ARRAY['preschool', 'elementary', 'middle_school', 'high_school'], ARRAY['administration'], ARRAY['audit_readiness'], ARRAY[]::text[], 'safe', '{"iep": "Preparedness maintained for compliance audits.", "parent": "The school keeps records in case of audits."}'::jsonb, 'active');