-- Batch 10: Speech, Language, AAC & Communication Supports (Items 136-150)
INSERT INTO public.iep_library_items (item_type, title, description, implementation_notes, domains, disability_tags, grade_band, setting_tags, topics, contraindications, idea_compliance_level, export_language, status)
VALUES
  ('accommodation', 'Augmentative and Alternative Communication (AAC) Device Access', 'Student has access to an AAC system to support expressive communication.', '["Ensure device is charged and accessible at all times", "Train staff on use and prompting hierarchy"]'::jsonb, ARRAY['communication'], ARRAY['autism', 'speech_language_impairment'], ARRAY['preschool', 'elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['aac'], ARRAY[]::text[], 'safe', '{"iep": "Access to AAC system to support expressive communication.", "parent": "Your child may use a communication device or system to express themselves."}'::jsonb, 'active'),
  ('accommodation', 'Modeling of AAC Use by Staff', 'Staff model appropriate use of the AAC system during instruction and interaction.', '["Model without requiring immediate response", "Use during natural routines"]'::jsonb, ARRAY['communication'], ARRAY['autism', 'speech_language_impairment'], ARRAY['preschool', 'elementary'], ARRAY['general_ed'], ARRAY['aac_modeling'], ARRAY[]::text[], 'safe', '{"iep": "Staff will model use of AAC to support language development.", "parent": "Adults will show your child how to use their communication system."}'::jsonb, 'active'),
  ('accommodation', 'Extended Wait Time for Responses', 'Student is given extended time to process and respond during communication.', '["Wait at least 5–10 seconds before prompting", "Avoid rushing or completing responses"]'::jsonb, ARRAY['communication'], ARRAY['speech_language_impairment', 'autism'], ARRAY['preschool', 'elementary', 'middle_school'], ARRAY['general_ed'], ARRAY['processing_time'], ARRAY[]::text[], 'safe', '{"iep": "Extended response time provided to support communication.", "parent": "Your child may be given extra time to respond when communicating."}'::jsonb, 'active'),
  ('accommodation', 'Visual Choice Boards', 'Visual choice boards are used to support expressive language and decision-making.', '["Limit choices to avoid overload", "Update choices regularly"]'::jsonb, ARRAY['communication'], ARRAY['autism', 'speech_language_impairment'], ARRAY['preschool', 'elementary'], ARRAY['general_ed'], ARRAY['expressive_language'], ARRAY[]::text[], 'safe', '{"iep": "Use of visual choice boards to support expressive communication.", "parent": "Your child may use pictures to make choices or communicate needs."}'::jsonb, 'active'),
  ('accommodation', 'Simplified Question Formats', 'Questions are simplified to reduce linguistic complexity.', '["Use yes/no or forced-choice when appropriate", "Gradually increase complexity"]'::jsonb, ARRAY['communication'], ARRAY['speech_language_impairment'], ARRAY['preschool', 'elementary'], ARRAY['general_ed'], ARRAY['receptive_language'], ARRAY[]::text[], 'safe', '{"iep": "Simplified question formats used to support comprehension.", "parent": "Teachers may ask simpler questions to help your child understand."}'::jsonb, 'active'),
  ('accommodation', 'Language-Rich Instructional Environment', 'Instruction includes intentional language modeling and expansion.', '["Expand on student utterances", "Embed language across activities"]'::jsonb, ARRAY['communication'], ARRAY['speech_language_impairment', 'autism'], ARRAY['preschool', 'elementary'], ARRAY['general_ed'], ARRAY['language_development'], ARRAY[]::text[], 'safe', '{"iep": "Language-rich instruction provided to support communication development.", "parent": "Teachers will model and expand language throughout the day."}'::jsonb, 'active'),
  ('accommodation', 'Explicit Vocabulary Instruction', 'Vocabulary is taught directly using multisensory strategies.', '["Use visuals, gestures, and repetition", "Review vocabulary frequently"]'::jsonb, ARRAY['communication', 'academics'], ARRAY['speech_language_impairment'], ARRAY['elementary', 'middle_school'], ARRAY['general_ed'], ARRAY['vocabulary'], ARRAY[]::text[], 'safe', '{"iep": "Explicit vocabulary instruction to support language comprehension.", "parent": "Your child may receive direct teaching of new words."}'::jsonb, 'active'),
  ('accommodation', 'Pragmatic Language Support', 'Instruction supports appropriate social use of language.', '["Use role-play and modeling", "Practice in natural contexts"]'::jsonb, ARRAY['communication', 'social_emotional'], ARRAY['autism'], ARRAY['elementary', 'middle_school'], ARRAY['small_group'], ARRAY['pragmatics'], ARRAY[]::text[], 'safe', '{"iep": "Support provided for pragmatic (social) language skills.", "parent": "Your child may practice social communication skills."}'::jsonb, 'active'),
  ('accommodation', 'Reduced Verbal Load During Instruction', 'Instruction limits excessive verbal information to reduce overload.', '["Pair with visuals", "Chunk information"]'::jsonb, ARRAY['communication'], ARRAY['autism'], ARRAY['preschool', 'elementary'], ARRAY['general_ed'], ARRAY['auditory_processing'], ARRAY[]::text[], 'safe', '{"iep": "Reduced verbal load during instruction to support comprehension.", "parent": "Teachers may simplify how much verbal information is given."}'::jsonb, 'active'),
  ('accommodation', 'Speech-to-Text for Expressive Language', 'Speech-to-text technology supports expressive language and written output.', '["Provide training", "Allow editing time"]'::jsonb, ARRAY['communication', 'assistive_technology'], ARRAY['speech_language_impairment', 'specific_learning_disability'], ARRAY['middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['assistive_tech'], ARRAY[]::text[], 'safe', '{"iep": "Speech-to-text technology provided to support expressive communication.", "parent": "Your child may speak instead of typing or writing."}'::jsonb, 'active'),
  ('accommodation', 'Text-to-Speech for Receptive Language', 'Text-to-speech tools support comprehension of written language.', '["Ensure accessibility features are enabled", "Pair with comprehension checks"]'::jsonb, ARRAY['communication', 'assistive_technology'], ARRAY['speech_language_impairment', 'specific_learning_disability'], ARRAY['elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['reading_support'], ARRAY[]::text[], 'safe', '{"iep": "Text-to-speech tools used to support language comprehension.", "parent": "Your child may listen to text being read aloud."}'::jsonb, 'active'),
  ('accommodation', 'Communication Partner Training', 'Staff receive training on effective communication strategies for the student.', '["Include prompting hierarchies", "Review strategies regularly"]'::jsonb, ARRAY['communication'], ARRAY['autism', 'speech_language_impairment'], ARRAY['preschool', 'elementary', 'middle_school'], ARRAY['general_ed'], ARRAY['staff_training'], ARRAY[]::text[], 'safe', '{"iep": "Staff trained to support effective communication with the student.", "parent": "School staff will be trained on how best to communicate with your child."}'::jsonb, 'active'),
  ('accommodation', 'Alternative Response Modes', 'Student may respond using gestures, visuals, or AAC instead of speech.', '["Honor all functional communication", "Reinforce attempts"]'::jsonb, ARRAY['communication'], ARRAY['speech_language_impairment', 'autism'], ARRAY['preschool', 'elementary', 'middle_school'], ARRAY['general_ed'], ARRAY['expressive_language'], ARRAY[]::text[], 'safe', '{"iep": "Alternative response modes accepted to demonstrate communication.", "parent": "Your child may communicate using pictures, gestures, or devices."}'::jsonb, 'active'),
  ('accommodation', 'Receptive Language Comprehension Checks', 'Staff check for understanding after giving directions or instruction.', '["Ask student to demonstrate or restate", "Clarify as needed"]'::jsonb, ARRAY['communication'], ARRAY['speech_language_impairment'], ARRAY['preschool', 'elementary', 'middle_school'], ARRAY['general_ed'], ARRAY['comprehension'], ARRAY[]::text[], 'safe', '{"iep": "Regular comprehension checks to ensure understanding.", "parent": "Teachers will make sure your child understands directions."}'::jsonb, 'active'),
  ('accommodation', 'Functional Communication Goal Alignment', 'Classroom communication supports align with speech-language IEP goals.', '["Coordinate with SLP", "Ensure consistency across staff"]'::jsonb, ARRAY['communication'], ARRAY['speech_language_impairment', 'autism'], ARRAY['preschool', 'elementary', 'middle_school'], ARRAY['general_ed'], ARRAY['goal_alignment'], ARRAY[]::text[], 'safe', '{"iep": "Communication supports aligned with speech-language goals.", "parent": "School supports will match your child''s communication goals."}'::jsonb, 'active');

-- Batch 11: Autism-Specific & Neurodivergent-Affirming Supports (Items 151-165)
INSERT INTO public.iep_library_items (item_type, title, description, implementation_notes, domains, disability_tags, grade_band, setting_tags, topics, contraindications, idea_compliance_level, export_language, status)
VALUES
  ('accommodation', 'Structured Teaching Environment', 'Instruction is delivered using predictable structure and routines.', '["Use consistent routines", "Clearly define work and break areas"]'::jsonb, ARRAY['environmental_access', 'behavior'], ARRAY['autism'], ARRAY['preschool', 'elementary', 'middle_school'], ARRAY['general_ed'], ARRAY['structure'], ARRAY[]::text[], 'safe', '{"iep": "Structured teaching environment implemented to support learning.", "parent": "Your child''s classroom may follow predictable routines."}'::jsonb, 'active'),
  ('accommodation', 'Visual Work Systems', 'Visual systems clarify what work is required and when it is finished.', '["Use clear start/finish cues", "Teach system explicitly"]'::jsonb, ARRAY['attention_executive_function'], ARRAY['autism'], ARRAY['preschool', 'elementary'], ARRAY['general_ed'], ARRAY['work_completion'], ARRAY[]::text[], 'safe', '{"iep": "Use of visual work systems to support task completion.", "parent": "Your child may use visual cues to know when work is done."}'::jsonb, 'active'),
  ('accommodation', 'Reduced Sensory Load During Instruction', 'Sensory input is minimized during instruction to improve focus.', '["Limit competing stimuli", "Use neutral visuals"]'::jsonb, ARRAY['sensory_regulation'], ARRAY['autism'], ARRAY['preschool', 'elementary'], ARRAY['general_ed'], ARRAY['sensory_support'], ARRAY[]::text[], 'safe', '{"iep": "Reduced sensory load during instruction.", "parent": "The classroom may be adjusted to reduce sensory distractions."}'::jsonb, 'active'),
  ('accommodation', 'Predictable Adult Responses', 'Staff respond consistently to behavior and communication.', '["Ensure consistency across staff", "Review procedures regularly"]'::jsonb, ARRAY['behavior'], ARRAY['autism'], ARRAY['preschool', 'elementary', 'middle_school'], ARRAY['general_ed'], ARRAY['consistency'], ARRAY[]::text[], 'safe', '{"iep": "Predictable adult responses provided to support regulation.", "parent": "Staff will respond consistently to your child."}'::jsonb, 'active'),
  ('accommodation', 'Strength-Based Instruction', 'Instruction incorporates the student''s interests and strengths.', '["Identify motivating interests", "Embed interests into lessons"]'::jsonb, ARRAY['academics', 'behavior'], ARRAY['autism'], ARRAY['preschool', 'elementary', 'middle_school'], ARRAY['general_ed'], ARRAY['engagement'], ARRAY[]::text[], 'safe', '{"iep": "Strength-based instruction used to increase engagement.", "parent": "Teachers may use your child''s interests to help them learn."}'::jsonb, 'active'),
  ('accommodation', 'Explicit Teaching of Hidden Curriculum', 'Unspoken social and classroom rules are taught explicitly.', '["Use visuals and role-play", "Review rules regularly"]'::jsonb, ARRAY['social_emotional', 'communication'], ARRAY['autism'], ARRAY['elementary', 'middle_school'], ARRAY['small_group'], ARRAY['hidden_curriculum'], ARRAY[]::text[], 'safe', '{"iep": "Explicit instruction of social and classroom expectations.", "parent": "Your child may be taught social rules directly."}'::jsonb, 'active'),
  ('accommodation', 'Visual Transition Supports', 'Visual cues support transitions between activities.', '["Use countdowns or icons", "Pair with verbal warnings"]'::jsonb, ARRAY['transitions'], ARRAY['autism'], ARRAY['preschool', 'elementary'], ARRAY['general_ed'], ARRAY['transition_support'], ARRAY[]::text[], 'safe', '{"iep": "Visual supports provided for transitions.", "parent": "Your child may see pictures or timers to prepare for transitions."}'::jsonb, 'active'),
  ('accommodation', 'Regulation Check-Ins', 'Student participates in regular emotional or sensory check-ins.', '["Use simple rating scales", "Respond proactively to needs"]'::jsonb, ARRAY['emotional_regulation'], ARRAY['autism'], ARRAY['preschool', 'elementary', 'middle_school'], ARRAY['general_ed'], ARRAY['self_regulation'], ARRAY[]::text[], 'safe', '{"iep": "Regular regulation check-ins provided throughout the day.", "parent": "Staff may check in to see how your child is feeling."}'::jsonb, 'active'),
  ('accommodation', 'Low-Demand Entry to Tasks', 'Tasks begin with low-demand components to reduce resistance.', '["Start with preferred or easy tasks", "Increase demand gradually"]'::jsonb, ARRAY['behavior'], ARRAY['autism'], ARRAY['preschool', 'elementary'], ARRAY['general_ed'], ARRAY['task_initiation'], ARRAY[]::text[], 'safe', '{"iep": "Low-demand task entry used to support task initiation.", "parent": "Tasks may start easy and build up gradually."}'::jsonb, 'active'),
  ('accommodation', 'Predictable Visual Boundaries', 'Physical and visual boundaries are clearly defined in the environment.', '["Use rugs, tape, or dividers", "Teach expectations for each space"]'::jsonb, ARRAY['environmental_access'], ARRAY['autism'], ARRAY['preschool', 'elementary'], ARRAY['general_ed'], ARRAY['environmental_structure'], ARRAY[]::text[], 'safe', '{"iep": "Visual boundaries used to define classroom spaces.", "parent": "The classroom may have clear areas for different activities."}'::jsonb, 'active'),
  ('accommodation', 'Functional Behavior Understanding', 'Staff use a functional understanding of behavior to guide responses.', '["Review behavior data", "Adjust strategies accordingly"]'::jsonb, ARRAY['behavior'], ARRAY['autism'], ARRAY['preschool', 'elementary', 'middle_school'], ARRAY['general_ed'], ARRAY['behavior_analysis'], ARRAY[]::text[], 'safe', '{"iep": "Behavior responses guided by functional understanding.", "parent": "Staff will look at why behaviors happen before responding."}'::jsonb, 'active'),
  ('accommodation', 'Predictable Reinforcement Systems', 'Reinforcement systems are predictable and transparent.', '["Define expectations clearly", "Review reinforcement schedules"]'::jsonb, ARRAY['behavior'], ARRAY['autism'], ARRAY['preschool', 'elementary'], ARRAY['general_ed'], ARRAY['reinforcement'], ARRAY[]::text[], 'safe', '{"iep": "Predictable reinforcement systems used to support behavior.", "parent": "Your child may earn rewards through a consistent system."}'::jsonb, 'active'),
  ('accommodation', 'Flexible Response Expectations', 'Student is not required to respond verbally when alternative communication is appropriate.', '["Honor AAC and nonverbal communication", "Avoid forcing speech"]'::jsonb, ARRAY['communication'], ARRAY['autism'], ARRAY['preschool', 'elementary', 'middle_school'], ARRAY['general_ed'], ARRAY['neurodiversity_affirming'], ARRAY[]::text[], 'safe', '{"iep": "Flexible response expectations honoring alternative communication.", "parent": "Your child will not be forced to speak if another way works better."}'::jsonb, 'active'),
  ('accommodation', 'Gradual Independence Building', 'Supports are faded systematically to build independence.', '["Define fading criteria", "Monitor progress closely"]'::jsonb, ARRAY['attention_executive_function'], ARRAY['autism'], ARRAY['elementary', 'middle_school'], ARRAY['general_ed'], ARRAY['independence'], ARRAY[]::text[], 'safe', '{"iep": "Systematic fading of supports to build independence.", "parent": "Supports will be reduced gradually as your child gains skills."}'::jsonb, 'active'),
  ('accommodation', 'Neurodivergent-Affirming Language Use', 'Staff use respectful, affirming language when referring to neurodivergent traits.', '["Avoid deficit-based language", "Model respect and inclusion"]'::jsonb, ARRAY['social_emotional'], ARRAY['autism'], ARRAY['preschool', 'elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['inclusion'], ARRAY[]::text[], 'safe', '{"iep": "Use of neurodivergent-affirming language by staff.", "parent": "Staff will speak about your child in respectful, affirming ways."}'::jsonb, 'active');