
-- Enable RLS on all 146 unprotected public tables
ALTER TABLE public.abas_program_priority_weights ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ablls_benchmarks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ablls_domains ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ablls_programs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ablls_skill_areas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.afls_benchmarks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.afls_domains ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.afls_programs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.afls_skill_areas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assessment_goal_recommendation_map ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assessment_library_registry ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.automation_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.beacon_ai_feedback ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.beacon_ai_suggestions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.behavior_category_normalization ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.behavior_decoded_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.behavior_decoded_sync_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.behavior_function_aliases ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.behavior_function_bip_strategy_map ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.behavior_function_goal_map ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.behavior_goal_map ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.behavior_replacement_map ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.behavior_risk_response_map ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.behavior_severity_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.behavior_support_recommendation_map ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.behavior_topography_aliases ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.behavior_topography_strategy_map ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bip_export_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bip_narrative_modifiers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bip_narrative_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bip_refinement_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bip_render_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bip_support_library ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.board_themes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bops_cfi_classroom_models ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bops_cfi_program_map ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bops_combo_registry ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bops_core_archetypes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bops_dual_constellation_registry ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bops_dual_constellations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bops_master_program_library ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bops_profile_program_map ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bops_profile_registry ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bops_question_bank ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bops_triadic_registry ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.class_contingencies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.class_score_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.classroom_board_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.classroom_feed_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.classroom_game_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.classroom_public_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.classroom_teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.classroom_wishlists ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clinical_framework_crosswalk ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clinical_goal_recommendation_map ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.curriculum_source_registry ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_student_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dayc_benchmark_steps ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dayc_objectives ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dayc_programs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.district_visibility_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.esdm_benchmark_steps ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.esdm_objectives ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.esdm_programs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.form_attachments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.form_definitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.form_exports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.form_field_mappings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.form_packet_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.form_packets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.form_response_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.form_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.game_modes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.game_themes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.generated_goal_targets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.goal_intervention_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.library_crosswalk_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.library_domains ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.library_goal_bank ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.library_goal_objectives ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.library_subdomains ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.message_reactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mtss_escalation_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mtss_escalation_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notification_dispatch_queue ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notification_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notification_providers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.package_definition_forms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.package_definitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.parent_notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.parent_question_replies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.parent_report_profile_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.parent_report_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.post_student_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profile_pending_reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profile_update_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reinforcement_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.replacement_behavior_library ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.report_definitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.report_exports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.report_generation_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reporting_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reward_effectiveness_observations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.school_culture_prompts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.school_leaderboards ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.socially_savvy_benchmark_steps ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.socially_savvy_objectives ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.socially_savvy_programs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sponsor_contributions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sponsored_rewards ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sponsors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_assessment_pairwise_comparisons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_assessment_raw_scores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_assessment_scoring_status ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_attendance_status ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_board_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_bops_scores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_game_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_game_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_portal_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_programming_data_points ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_reinforcement_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_reinforcement_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_reinforcement_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_reinforcer_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_reward_goals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_streaks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_team_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_token_boards ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_unlocks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supervisor_visibility_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.team_score_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.thread_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.thread_mentions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.threads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.token_boards ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.unlock_catalog ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vineland_age_bands ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vineland_domains ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vineland_forms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vineland_norm_lookup_composites ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vineland_norm_lookup_domains ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vineland_norm_lookup_subdomains ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vineland_subdomains ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.weekly_student_reports ENABLE ROW LEVEL SECURITY;

-- Student-scoped policies (tables with student_id column)
CREATE POLICY "behavior_decoded_links_student_access" ON public.behavior_decoded_links FOR ALL TO authenticated USING (has_student_access(student_id, auth.uid()) OR is_admin(auth.uid())) WITH CHECK (has_student_access(student_id, auth.uid()) OR is_admin(auth.uid()));
CREATE POLICY "behavior_decoded_sync_log_student_access" ON public.behavior_decoded_sync_log FOR ALL TO authenticated USING (has_student_access(student_id, auth.uid()) OR is_admin(auth.uid())) WITH CHECK (has_student_access(student_id, auth.uid()) OR is_admin(auth.uid()));
CREATE POLICY "daily_student_snapshots_student_access" ON public.daily_student_snapshots FOR ALL TO authenticated USING (has_student_access(student_id, auth.uid()) OR is_admin(auth.uid())) WITH CHECK (has_student_access(student_id, auth.uid()) OR is_admin(auth.uid()));
CREATE POLICY "mtss_escalation_results_student_access" ON public.mtss_escalation_results FOR ALL TO authenticated USING (has_student_access(student_id, auth.uid()) OR is_admin(auth.uid())) WITH CHECK (has_student_access(student_id, auth.uid()) OR is_admin(auth.uid()));
CREATE POLICY "parent_notifications_student_access" ON public.parent_notifications FOR ALL TO authenticated USING (has_student_access(student_id, auth.uid()) OR is_admin(auth.uid())) WITH CHECK (has_student_access(student_id, auth.uid()) OR is_admin(auth.uid()));
CREATE POLICY "post_student_tags_student_access" ON public.post_student_tags FOR ALL TO authenticated USING (has_student_access(student_id, auth.uid()) OR is_admin(auth.uid())) WITH CHECK (has_student_access(student_id, auth.uid()) OR is_admin(auth.uid()));
CREATE POLICY "reward_effectiveness_observations_student_access" ON public.reward_effectiveness_observations FOR ALL TO authenticated USING (has_student_access(student_id, auth.uid()) OR is_admin(auth.uid())) WITH CHECK (has_student_access(student_id, auth.uid()) OR is_admin(auth.uid()));
CREATE POLICY "student_attendance_status_student_access" ON public.student_attendance_status FOR ALL TO authenticated USING (has_student_access(student_id, auth.uid()) OR is_admin(auth.uid())) WITH CHECK (has_student_access(student_id, auth.uid()) OR is_admin(auth.uid()));
CREATE POLICY "student_board_profiles_student_access" ON public.student_board_profiles FOR ALL TO authenticated USING (has_student_access(student_id, auth.uid()) OR is_admin(auth.uid())) WITH CHECK (has_student_access(student_id, auth.uid()) OR is_admin(auth.uid()));
CREATE POLICY "student_bops_scores_student_access" ON public.student_bops_scores FOR ALL TO authenticated USING (has_student_access(student_id, auth.uid()) OR is_admin(auth.uid())) WITH CHECK (has_student_access(student_id, auth.uid()) OR is_admin(auth.uid()));
CREATE POLICY "student_game_profiles_student_access" ON public.student_game_profiles FOR ALL TO authenticated USING (has_student_access(student_id, auth.uid()) OR is_admin(auth.uid())) WITH CHECK (has_student_access(student_id, auth.uid()) OR is_admin(auth.uid()));
CREATE POLICY "student_game_state_student_access" ON public.student_game_state FOR ALL TO authenticated USING (has_student_access(student_id, auth.uid()) OR is_admin(auth.uid())) WITH CHECK (has_student_access(student_id, auth.uid()) OR is_admin(auth.uid()));
CREATE POLICY "student_portal_accounts_student_access" ON public.student_portal_accounts FOR ALL TO authenticated USING (has_student_access(student_id, auth.uid()) OR is_admin(auth.uid())) WITH CHECK (has_student_access(student_id, auth.uid()) OR is_admin(auth.uid()));
CREATE POLICY "student_programming_data_points_student_access" ON public.student_programming_data_points FOR ALL TO authenticated USING (has_student_access(student_id, auth.uid()) OR is_admin(auth.uid())) WITH CHECK (has_student_access(student_id, auth.uid()) OR is_admin(auth.uid()));
CREATE POLICY "student_reinforcement_plans_student_access" ON public.student_reinforcement_plans FOR ALL TO authenticated USING (has_student_access(student_id, auth.uid()) OR is_admin(auth.uid())) WITH CHECK (has_student_access(student_id, auth.uid()) OR is_admin(auth.uid()));
CREATE POLICY "student_reinforcement_profiles_student_access" ON public.student_reinforcement_profiles FOR ALL TO authenticated USING (has_student_access(student_id, auth.uid()) OR is_admin(auth.uid())) WITH CHECK (has_student_access(student_id, auth.uid()) OR is_admin(auth.uid()));
CREATE POLICY "student_reinforcement_rules_student_access" ON public.student_reinforcement_rules FOR ALL TO authenticated USING (has_student_access(student_id, auth.uid()) OR is_admin(auth.uid())) WITH CHECK (has_student_access(student_id, auth.uid()) OR is_admin(auth.uid()));
CREATE POLICY "student_reinforcer_preferences_student_access" ON public.student_reinforcer_preferences FOR ALL TO authenticated USING (has_student_access(student_id, auth.uid()) OR is_admin(auth.uid())) WITH CHECK (has_student_access(student_id, auth.uid()) OR is_admin(auth.uid()));
CREATE POLICY "student_reward_goals_student_access" ON public.student_reward_goals FOR ALL TO authenticated USING (has_student_access(student_id, auth.uid()) OR is_admin(auth.uid())) WITH CHECK (has_student_access(student_id, auth.uid()) OR is_admin(auth.uid()));
CREATE POLICY "student_streaks_student_access" ON public.student_streaks FOR ALL TO authenticated USING (has_student_access(student_id, auth.uid()) OR is_admin(auth.uid())) WITH CHECK (has_student_access(student_id, auth.uid()) OR is_admin(auth.uid()));
CREATE POLICY "student_team_assignments_student_access" ON public.student_team_assignments FOR ALL TO authenticated USING (has_student_access(student_id, auth.uid()) OR is_admin(auth.uid())) WITH CHECK (has_student_access(student_id, auth.uid()) OR is_admin(auth.uid()));
CREATE POLICY "student_token_boards_student_access" ON public.student_token_boards FOR ALL TO authenticated USING (has_student_access(student_id, auth.uid()) OR is_admin(auth.uid())) WITH CHECK (has_student_access(student_id, auth.uid()) OR is_admin(auth.uid()));
CREATE POLICY "student_unlocks_student_access" ON public.student_unlocks FOR ALL TO authenticated USING (has_student_access(student_id, auth.uid()) OR is_admin(auth.uid())) WITH CHECK (has_student_access(student_id, auth.uid()) OR is_admin(auth.uid()));
CREATE POLICY "token_boards_student_access" ON public.token_boards FOR ALL TO authenticated USING (has_student_access(student_id, auth.uid()) OR is_admin(auth.uid())) WITH CHECK (has_student_access(student_id, auth.uid()) OR is_admin(auth.uid()));
CREATE POLICY "weekly_student_reports_student_access" ON public.weekly_student_reports FOR ALL TO authenticated USING (has_student_access(student_id, auth.uid()) OR is_admin(auth.uid())) WITH CHECK (has_student_access(student_id, auth.uid()) OR is_admin(auth.uid()));

-- Classroom-scoped policies
CREATE POLICY "class_contingencies_read" ON public.class_contingencies FOR SELECT TO authenticated USING (true);
CREATE POLICY "class_contingencies_write" ON public.class_contingencies FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "class_contingencies_update" ON public.class_contingencies FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "class_contingencies_delete" ON public.class_contingencies FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "class_score_snapshots_read" ON public.class_score_snapshots FOR SELECT TO authenticated USING (true);
CREATE POLICY "class_score_snapshots_write" ON public.class_score_snapshots FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "class_score_snapshots_update" ON public.class_score_snapshots FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "class_score_snapshots_delete" ON public.class_score_snapshots FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "classroom_board_settings_read" ON public.classroom_board_settings FOR SELECT TO authenticated USING (true);
CREATE POLICY "classroom_board_settings_write" ON public.classroom_board_settings FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "classroom_board_settings_update" ON public.classroom_board_settings FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "classroom_board_settings_delete" ON public.classroom_board_settings FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "classroom_feed_posts_read" ON public.classroom_feed_posts FOR SELECT TO authenticated USING (true);
CREATE POLICY "classroom_feed_posts_write" ON public.classroom_feed_posts FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "classroom_feed_posts_update" ON public.classroom_feed_posts FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "classroom_feed_posts_delete" ON public.classroom_feed_posts FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "classroom_game_settings_read" ON public.classroom_game_settings FOR SELECT TO authenticated USING (true);
CREATE POLICY "classroom_game_settings_write" ON public.classroom_game_settings FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "classroom_game_settings_update" ON public.classroom_game_settings FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "classroom_game_settings_delete" ON public.classroom_game_settings FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "classroom_public_links_read" ON public.classroom_public_links FOR SELECT TO authenticated USING (true);
CREATE POLICY "classroom_public_links_write" ON public.classroom_public_links FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "classroom_public_links_update" ON public.classroom_public_links FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "classroom_public_links_delete" ON public.classroom_public_links FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "classroom_teams_read" ON public.classroom_teams FOR SELECT TO authenticated USING (true);
CREATE POLICY "classroom_teams_write" ON public.classroom_teams FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "classroom_teams_update" ON public.classroom_teams FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "classroom_teams_delete" ON public.classroom_teams FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "classroom_wishlists_read" ON public.classroom_wishlists FOR SELECT TO authenticated USING (true);
CREATE POLICY "classroom_wishlists_write" ON public.classroom_wishlists FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "classroom_wishlists_update" ON public.classroom_wishlists FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "classroom_wishlists_delete" ON public.classroom_wishlists FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "team_score_snapshots_read" ON public.team_score_snapshots FOR SELECT TO authenticated USING (true);
CREATE POLICY "team_score_snapshots_write" ON public.team_score_snapshots FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "team_score_snapshots_update" ON public.team_score_snapshots FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "team_score_snapshots_delete" ON public.team_score_snapshots FOR DELETE TO authenticated USING (is_admin(auth.uid()));

-- Assessment sub-table policies (join through student_assessments)
CREATE POLICY "student_assessment_pairwise_comparisons_access" ON public.student_assessment_pairwise_comparisons FOR ALL TO authenticated USING (EXISTS (SELECT 1 FROM public.student_assessments sa WHERE sa.id = student_assessment_pairwise_comparisons.student_assessment_id AND (has_student_access(sa.student_id, auth.uid()) OR is_admin(auth.uid())))) WITH CHECK (EXISTS (SELECT 1 FROM public.student_assessments sa WHERE sa.id = student_assessment_pairwise_comparisons.student_assessment_id AND (has_student_access(sa.student_id, auth.uid()) OR is_admin(auth.uid()))));
CREATE POLICY "student_assessment_raw_scores_access" ON public.student_assessment_raw_scores FOR ALL TO authenticated USING (EXISTS (SELECT 1 FROM public.student_assessments sa WHERE sa.id = student_assessment_raw_scores.student_assessment_id AND (has_student_access(sa.student_id, auth.uid()) OR is_admin(auth.uid())))) WITH CHECK (EXISTS (SELECT 1 FROM public.student_assessments sa WHERE sa.id = student_assessment_raw_scores.student_assessment_id AND (has_student_access(sa.student_id, auth.uid()) OR is_admin(auth.uid()))));
CREATE POLICY "student_assessment_scoring_status_access" ON public.student_assessment_scoring_status FOR ALL TO authenticated USING (EXISTS (SELECT 1 FROM public.student_assessments sa WHERE sa.id = student_assessment_scoring_status.student_assessment_id AND (has_student_access(sa.student_id, auth.uid()) OR is_admin(auth.uid())))) WITH CHECK (EXISTS (SELECT 1 FROM public.student_assessments sa WHERE sa.id = student_assessment_scoring_status.student_assessment_id AND (has_student_access(sa.student_id, auth.uid()) OR is_admin(auth.uid()))));

-- User-scoped policies
CREATE POLICY "message_reactions_access" ON public.message_reactions FOR ALL TO authenticated USING (user_id = auth.uid() OR is_admin(auth.uid())) WITH CHECK (user_id = auth.uid() OR is_admin(auth.uid()));
CREATE POLICY "thread_members_access" ON public.thread_members FOR ALL TO authenticated USING (user_id = auth.uid() OR is_admin(auth.uid())) WITH CHECK (user_id = auth.uid() OR is_admin(auth.uid()));

-- Messaging policies
CREATE POLICY "threads_read" ON public.threads FOR SELECT TO authenticated USING (true);
CREATE POLICY "threads_write" ON public.threads FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "threads_update" ON public.threads FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "threads_delete" ON public.threads FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "messages_read" ON public.messages FOR SELECT TO authenticated USING (true);
CREATE POLICY "messages_insert" ON public.messages FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "messages_update" ON public.messages FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "messages_delete" ON public.messages FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "thread_mentions_read" ON public.thread_mentions FOR SELECT TO authenticated USING (true);
CREATE POLICY "thread_mentions_write" ON public.thread_mentions FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "thread_mentions_update" ON public.thread_mentions FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "thread_mentions_delete" ON public.thread_mentions FOR DELETE TO authenticated USING (is_admin(auth.uid()));

-- Reference/library table policies (authenticated read, admin write)
CREATE POLICY "abas_program_priority_weights_read" ON public.abas_program_priority_weights FOR SELECT TO authenticated USING (true);
CREATE POLICY "abas_program_priority_weights_admin_write" ON public.abas_program_priority_weights FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "abas_program_priority_weights_admin_update" ON public.abas_program_priority_weights FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "abas_program_priority_weights_admin_delete" ON public.abas_program_priority_weights FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "ablls_benchmarks_read" ON public.ablls_benchmarks FOR SELECT TO authenticated USING (true);
CREATE POLICY "ablls_benchmarks_admin_write" ON public.ablls_benchmarks FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "ablls_benchmarks_admin_update" ON public.ablls_benchmarks FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "ablls_benchmarks_admin_delete" ON public.ablls_benchmarks FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "ablls_domains_read" ON public.ablls_domains FOR SELECT TO authenticated USING (true);
CREATE POLICY "ablls_domains_admin_write" ON public.ablls_domains FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "ablls_domains_admin_update" ON public.ablls_domains FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "ablls_domains_admin_delete" ON public.ablls_domains FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "ablls_programs_read" ON public.ablls_programs FOR SELECT TO authenticated USING (true);
CREATE POLICY "ablls_programs_admin_write" ON public.ablls_programs FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "ablls_programs_admin_update" ON public.ablls_programs FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "ablls_programs_admin_delete" ON public.ablls_programs FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "ablls_skill_areas_read" ON public.ablls_skill_areas FOR SELECT TO authenticated USING (true);
CREATE POLICY "ablls_skill_areas_admin_write" ON public.ablls_skill_areas FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "ablls_skill_areas_admin_update" ON public.ablls_skill_areas FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "ablls_skill_areas_admin_delete" ON public.ablls_skill_areas FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "afls_benchmarks_read" ON public.afls_benchmarks FOR SELECT TO authenticated USING (true);
CREATE POLICY "afls_benchmarks_admin_write" ON public.afls_benchmarks FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "afls_benchmarks_admin_update" ON public.afls_benchmarks FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "afls_benchmarks_admin_delete" ON public.afls_benchmarks FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "afls_domains_read" ON public.afls_domains FOR SELECT TO authenticated USING (true);
CREATE POLICY "afls_domains_admin_write" ON public.afls_domains FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "afls_domains_admin_update" ON public.afls_domains FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "afls_domains_admin_delete" ON public.afls_domains FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "afls_programs_read" ON public.afls_programs FOR SELECT TO authenticated USING (true);
CREATE POLICY "afls_programs_admin_write" ON public.afls_programs FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "afls_programs_admin_update" ON public.afls_programs FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "afls_programs_admin_delete" ON public.afls_programs FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "afls_skill_areas_read" ON public.afls_skill_areas FOR SELECT TO authenticated USING (true);
CREATE POLICY "afls_skill_areas_admin_write" ON public.afls_skill_areas FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "afls_skill_areas_admin_update" ON public.afls_skill_areas FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "afls_skill_areas_admin_delete" ON public.afls_skill_areas FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "assessment_goal_recommendation_map_read" ON public.assessment_goal_recommendation_map FOR SELECT TO authenticated USING (true);
CREATE POLICY "assessment_goal_recommendation_map_admin_write" ON public.assessment_goal_recommendation_map FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "assessment_goal_recommendation_map_admin_update" ON public.assessment_goal_recommendation_map FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "assessment_goal_recommendation_map_admin_delete" ON public.assessment_goal_recommendation_map FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "assessment_library_registry_read" ON public.assessment_library_registry FOR SELECT TO authenticated USING (true);
CREATE POLICY "assessment_library_registry_admin_write" ON public.assessment_library_registry FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "assessment_library_registry_admin_update" ON public.assessment_library_registry FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "assessment_library_registry_admin_delete" ON public.assessment_library_registry FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "automation_rules_read" ON public.automation_rules FOR SELECT TO authenticated USING (true);
CREATE POLICY "automation_rules_admin_write" ON public.automation_rules FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "automation_rules_admin_update" ON public.automation_rules FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "automation_rules_admin_delete" ON public.automation_rules FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "beacon_ai_feedback_read" ON public.beacon_ai_feedback FOR SELECT TO authenticated USING (true);
CREATE POLICY "beacon_ai_feedback_admin_write" ON public.beacon_ai_feedback FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "beacon_ai_feedback_admin_update" ON public.beacon_ai_feedback FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "beacon_ai_feedback_admin_delete" ON public.beacon_ai_feedback FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "beacon_ai_suggestions_read" ON public.beacon_ai_suggestions FOR SELECT TO authenticated USING (true);
CREATE POLICY "beacon_ai_suggestions_admin_write" ON public.beacon_ai_suggestions FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "beacon_ai_suggestions_admin_update" ON public.beacon_ai_suggestions FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "beacon_ai_suggestions_admin_delete" ON public.beacon_ai_suggestions FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "behavior_category_normalization_read" ON public.behavior_category_normalization FOR SELECT TO authenticated USING (true);
CREATE POLICY "behavior_category_normalization_admin_write" ON public.behavior_category_normalization FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "behavior_category_normalization_admin_update" ON public.behavior_category_normalization FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "behavior_category_normalization_admin_delete" ON public.behavior_category_normalization FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "behavior_function_aliases_read" ON public.behavior_function_aliases FOR SELECT TO authenticated USING (true);
CREATE POLICY "behavior_function_aliases_admin_write" ON public.behavior_function_aliases FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "behavior_function_aliases_admin_update" ON public.behavior_function_aliases FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "behavior_function_aliases_admin_delete" ON public.behavior_function_aliases FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "behavior_function_bip_strategy_map_read" ON public.behavior_function_bip_strategy_map FOR SELECT TO authenticated USING (true);
CREATE POLICY "behavior_function_bip_strategy_map_admin_write" ON public.behavior_function_bip_strategy_map FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "behavior_function_bip_strategy_map_admin_update" ON public.behavior_function_bip_strategy_map FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "behavior_function_bip_strategy_map_admin_delete" ON public.behavior_function_bip_strategy_map FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "behavior_function_goal_map_read" ON public.behavior_function_goal_map FOR SELECT TO authenticated USING (true);
CREATE POLICY "behavior_function_goal_map_admin_write" ON public.behavior_function_goal_map FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "behavior_function_goal_map_admin_update" ON public.behavior_function_goal_map FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "behavior_function_goal_map_admin_delete" ON public.behavior_function_goal_map FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "behavior_goal_map_read" ON public.behavior_goal_map FOR SELECT TO authenticated USING (true);
CREATE POLICY "behavior_goal_map_admin_write" ON public.behavior_goal_map FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "behavior_goal_map_admin_update" ON public.behavior_goal_map FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "behavior_goal_map_admin_delete" ON public.behavior_goal_map FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "behavior_replacement_map_read" ON public.behavior_replacement_map FOR SELECT TO authenticated USING (true);
CREATE POLICY "behavior_replacement_map_admin_write" ON public.behavior_replacement_map FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "behavior_replacement_map_admin_update" ON public.behavior_replacement_map FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "behavior_replacement_map_admin_delete" ON public.behavior_replacement_map FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "behavior_risk_response_map_read" ON public.behavior_risk_response_map FOR SELECT TO authenticated USING (true);
CREATE POLICY "behavior_risk_response_map_admin_write" ON public.behavior_risk_response_map FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "behavior_risk_response_map_admin_update" ON public.behavior_risk_response_map FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "behavior_risk_response_map_admin_delete" ON public.behavior_risk_response_map FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "behavior_severity_profiles_read" ON public.behavior_severity_profiles FOR SELECT TO authenticated USING (true);
CREATE POLICY "behavior_severity_profiles_admin_write" ON public.behavior_severity_profiles FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "behavior_severity_profiles_admin_update" ON public.behavior_severity_profiles FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "behavior_severity_profiles_admin_delete" ON public.behavior_severity_profiles FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "behavior_support_recommendation_map_read" ON public.behavior_support_recommendation_map FOR SELECT TO authenticated USING (true);
CREATE POLICY "behavior_support_recommendation_map_admin_write" ON public.behavior_support_recommendation_map FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "behavior_support_recommendation_map_admin_update" ON public.behavior_support_recommendation_map FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "behavior_support_recommendation_map_admin_delete" ON public.behavior_support_recommendation_map FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "behavior_topography_aliases_read" ON public.behavior_topography_aliases FOR SELECT TO authenticated USING (true);
CREATE POLICY "behavior_topography_aliases_admin_write" ON public.behavior_topography_aliases FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "behavior_topography_aliases_admin_update" ON public.behavior_topography_aliases FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "behavior_topography_aliases_admin_delete" ON public.behavior_topography_aliases FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "behavior_topography_strategy_map_read" ON public.behavior_topography_strategy_map FOR SELECT TO authenticated USING (true);
CREATE POLICY "behavior_topography_strategy_map_admin_write" ON public.behavior_topography_strategy_map FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "behavior_topography_strategy_map_admin_update" ON public.behavior_topography_strategy_map FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "behavior_topography_strategy_map_admin_delete" ON public.behavior_topography_strategy_map FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "bip_export_jobs_read" ON public.bip_export_jobs FOR SELECT TO authenticated USING (true);
CREATE POLICY "bip_export_jobs_admin_write" ON public.bip_export_jobs FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "bip_export_jobs_admin_update" ON public.bip_export_jobs FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "bip_export_jobs_admin_delete" ON public.bip_export_jobs FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "bip_narrative_modifiers_read" ON public.bip_narrative_modifiers FOR SELECT TO authenticated USING (true);
CREATE POLICY "bip_narrative_modifiers_admin_write" ON public.bip_narrative_modifiers FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "bip_narrative_modifiers_admin_update" ON public.bip_narrative_modifiers FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "bip_narrative_modifiers_admin_delete" ON public.bip_narrative_modifiers FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "bip_narrative_templates_read" ON public.bip_narrative_templates FOR SELECT TO authenticated USING (true);
CREATE POLICY "bip_narrative_templates_admin_write" ON public.bip_narrative_templates FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "bip_narrative_templates_admin_update" ON public.bip_narrative_templates FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "bip_narrative_templates_admin_delete" ON public.bip_narrative_templates FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "bip_refinement_sessions_read" ON public.bip_refinement_sessions FOR SELECT TO authenticated USING (true);
CREATE POLICY "bip_refinement_sessions_admin_write" ON public.bip_refinement_sessions FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "bip_refinement_sessions_admin_update" ON public.bip_refinement_sessions FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "bip_refinement_sessions_admin_delete" ON public.bip_refinement_sessions FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "bip_render_templates_read" ON public.bip_render_templates FOR SELECT TO authenticated USING (true);
CREATE POLICY "bip_render_templates_admin_write" ON public.bip_render_templates FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "bip_render_templates_admin_update" ON public.bip_render_templates FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "bip_render_templates_admin_delete" ON public.bip_render_templates FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "bip_support_library_read" ON public.bip_support_library FOR SELECT TO authenticated USING (true);
CREATE POLICY "bip_support_library_admin_write" ON public.bip_support_library FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "bip_support_library_admin_update" ON public.bip_support_library FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "bip_support_library_admin_delete" ON public.bip_support_library FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "board_themes_read" ON public.board_themes FOR SELECT TO authenticated USING (true);
CREATE POLICY "board_themes_admin_write" ON public.board_themes FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "board_themes_admin_update" ON public.board_themes FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "board_themes_admin_delete" ON public.board_themes FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "bops_cfi_classroom_models_read" ON public.bops_cfi_classroom_models FOR SELECT TO authenticated USING (true);
CREATE POLICY "bops_cfi_classroom_models_admin_write" ON public.bops_cfi_classroom_models FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "bops_cfi_classroom_models_admin_update" ON public.bops_cfi_classroom_models FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "bops_cfi_classroom_models_admin_delete" ON public.bops_cfi_classroom_models FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "bops_cfi_program_map_read" ON public.bops_cfi_program_map FOR SELECT TO authenticated USING (true);
CREATE POLICY "bops_cfi_program_map_admin_write" ON public.bops_cfi_program_map FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "bops_cfi_program_map_admin_update" ON public.bops_cfi_program_map FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "bops_cfi_program_map_admin_delete" ON public.bops_cfi_program_map FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "bops_combo_registry_read" ON public.bops_combo_registry FOR SELECT TO authenticated USING (true);
CREATE POLICY "bops_combo_registry_admin_write" ON public.bops_combo_registry FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "bops_combo_registry_admin_update" ON public.bops_combo_registry FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "bops_combo_registry_admin_delete" ON public.bops_combo_registry FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "bops_core_archetypes_read" ON public.bops_core_archetypes FOR SELECT TO authenticated USING (true);
CREATE POLICY "bops_core_archetypes_admin_write" ON public.bops_core_archetypes FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "bops_core_archetypes_admin_update" ON public.bops_core_archetypes FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "bops_core_archetypes_admin_delete" ON public.bops_core_archetypes FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "bops_dual_constellation_registry_read" ON public.bops_dual_constellation_registry FOR SELECT TO authenticated USING (true);
CREATE POLICY "bops_dual_constellation_registry_admin_write" ON public.bops_dual_constellation_registry FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "bops_dual_constellation_registry_admin_update" ON public.bops_dual_constellation_registry FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "bops_dual_constellation_registry_admin_delete" ON public.bops_dual_constellation_registry FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "bops_dual_constellations_read" ON public.bops_dual_constellations FOR SELECT TO authenticated USING (true);
CREATE POLICY "bops_dual_constellations_admin_write" ON public.bops_dual_constellations FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "bops_dual_constellations_admin_update" ON public.bops_dual_constellations FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "bops_dual_constellations_admin_delete" ON public.bops_dual_constellations FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "bops_master_program_library_read" ON public.bops_master_program_library FOR SELECT TO authenticated USING (true);
CREATE POLICY "bops_master_program_library_admin_write" ON public.bops_master_program_library FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "bops_master_program_library_admin_update" ON public.bops_master_program_library FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "bops_master_program_library_admin_delete" ON public.bops_master_program_library FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "bops_profile_program_map_read" ON public.bops_profile_program_map FOR SELECT TO authenticated USING (true);
CREATE POLICY "bops_profile_program_map_admin_write" ON public.bops_profile_program_map FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "bops_profile_program_map_admin_update" ON public.bops_profile_program_map FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "bops_profile_program_map_admin_delete" ON public.bops_profile_program_map FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "bops_profile_registry_read" ON public.bops_profile_registry FOR SELECT TO authenticated USING (true);
CREATE POLICY "bops_profile_registry_admin_write" ON public.bops_profile_registry FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "bops_profile_registry_admin_update" ON public.bops_profile_registry FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "bops_profile_registry_admin_delete" ON public.bops_profile_registry FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "bops_question_bank_read" ON public.bops_question_bank FOR SELECT TO authenticated USING (true);
CREATE POLICY "bops_question_bank_admin_write" ON public.bops_question_bank FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "bops_question_bank_admin_update" ON public.bops_question_bank FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "bops_question_bank_admin_delete" ON public.bops_question_bank FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "bops_triadic_registry_read" ON public.bops_triadic_registry FOR SELECT TO authenticated USING (true);
CREATE POLICY "bops_triadic_registry_admin_write" ON public.bops_triadic_registry FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "bops_triadic_registry_admin_update" ON public.bops_triadic_registry FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "bops_triadic_registry_admin_delete" ON public.bops_triadic_registry FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "clinical_framework_crosswalk_read" ON public.clinical_framework_crosswalk FOR SELECT TO authenticated USING (true);
CREATE POLICY "clinical_framework_crosswalk_admin_write" ON public.clinical_framework_crosswalk FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "clinical_framework_crosswalk_admin_update" ON public.clinical_framework_crosswalk FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "clinical_framework_crosswalk_admin_delete" ON public.clinical_framework_crosswalk FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "clinical_goal_recommendation_map_read" ON public.clinical_goal_recommendation_map FOR SELECT TO authenticated USING (true);
CREATE POLICY "clinical_goal_recommendation_map_admin_write" ON public.clinical_goal_recommendation_map FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "clinical_goal_recommendation_map_admin_update" ON public.clinical_goal_recommendation_map FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "clinical_goal_recommendation_map_admin_delete" ON public.clinical_goal_recommendation_map FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "curriculum_source_registry_read" ON public.curriculum_source_registry FOR SELECT TO authenticated USING (true);
CREATE POLICY "curriculum_source_registry_admin_write" ON public.curriculum_source_registry FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "curriculum_source_registry_admin_update" ON public.curriculum_source_registry FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "curriculum_source_registry_admin_delete" ON public.curriculum_source_registry FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "dayc_benchmark_steps_read" ON public.dayc_benchmark_steps FOR SELECT TO authenticated USING (true);
CREATE POLICY "dayc_benchmark_steps_admin_write" ON public.dayc_benchmark_steps FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "dayc_benchmark_steps_admin_update" ON public.dayc_benchmark_steps FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "dayc_benchmark_steps_admin_delete" ON public.dayc_benchmark_steps FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "dayc_objectives_read" ON public.dayc_objectives FOR SELECT TO authenticated USING (true);
CREATE POLICY "dayc_objectives_admin_write" ON public.dayc_objectives FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "dayc_objectives_admin_update" ON public.dayc_objectives FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "dayc_objectives_admin_delete" ON public.dayc_objectives FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "dayc_programs_read" ON public.dayc_programs FOR SELECT TO authenticated USING (true);
CREATE POLICY "dayc_programs_admin_write" ON public.dayc_programs FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "dayc_programs_admin_update" ON public.dayc_programs FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "dayc_programs_admin_delete" ON public.dayc_programs FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "district_visibility_settings_read" ON public.district_visibility_settings FOR SELECT TO authenticated USING (true);
CREATE POLICY "district_visibility_settings_admin_write" ON public.district_visibility_settings FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "district_visibility_settings_admin_update" ON public.district_visibility_settings FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "district_visibility_settings_admin_delete" ON public.district_visibility_settings FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "esdm_benchmark_steps_read" ON public.esdm_benchmark_steps FOR SELECT TO authenticated USING (true);
CREATE POLICY "esdm_benchmark_steps_admin_write" ON public.esdm_benchmark_steps FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "esdm_benchmark_steps_admin_update" ON public.esdm_benchmark_steps FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "esdm_benchmark_steps_admin_delete" ON public.esdm_benchmark_steps FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "esdm_objectives_read" ON public.esdm_objectives FOR SELECT TO authenticated USING (true);
CREATE POLICY "esdm_objectives_admin_write" ON public.esdm_objectives FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "esdm_objectives_admin_update" ON public.esdm_objectives FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "esdm_objectives_admin_delete" ON public.esdm_objectives FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "esdm_programs_read" ON public.esdm_programs FOR SELECT TO authenticated USING (true);
CREATE POLICY "esdm_programs_admin_write" ON public.esdm_programs FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "esdm_programs_admin_update" ON public.esdm_programs FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "esdm_programs_admin_delete" ON public.esdm_programs FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "form_attachments_read" ON public.form_attachments FOR SELECT TO authenticated USING (true);
CREATE POLICY "form_attachments_admin_write" ON public.form_attachments FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "form_attachments_admin_update" ON public.form_attachments FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "form_attachments_admin_delete" ON public.form_attachments FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "form_definitions_read" ON public.form_definitions FOR SELECT TO authenticated USING (true);
CREATE POLICY "form_definitions_admin_write" ON public.form_definitions FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "form_definitions_admin_update" ON public.form_definitions FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "form_definitions_admin_delete" ON public.form_definitions FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "form_exports_read" ON public.form_exports FOR SELECT TO authenticated USING (true);
CREATE POLICY "form_exports_admin_write" ON public.form_exports FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "form_exports_admin_update" ON public.form_exports FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "form_exports_admin_delete" ON public.form_exports FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "form_field_mappings_read" ON public.form_field_mappings FOR SELECT TO authenticated USING (true);
CREATE POLICY "form_field_mappings_admin_write" ON public.form_field_mappings FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "form_field_mappings_admin_update" ON public.form_field_mappings FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "form_field_mappings_admin_delete" ON public.form_field_mappings FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "form_packet_items_read" ON public.form_packet_items FOR SELECT TO authenticated USING (true);
CREATE POLICY "form_packet_items_admin_write" ON public.form_packet_items FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "form_packet_items_admin_update" ON public.form_packet_items FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "form_packet_items_admin_delete" ON public.form_packet_items FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "form_packets_read" ON public.form_packets FOR SELECT TO authenticated USING (true);
CREATE POLICY "form_packets_admin_write" ON public.form_packets FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "form_packets_admin_update" ON public.form_packets FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "form_packets_admin_delete" ON public.form_packets FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "form_response_versions_read" ON public.form_response_versions FOR SELECT TO authenticated USING (true);
CREATE POLICY "form_response_versions_admin_write" ON public.form_response_versions FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "form_response_versions_admin_update" ON public.form_response_versions FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "form_response_versions_admin_delete" ON public.form_response_versions FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "form_versions_read" ON public.form_versions FOR SELECT TO authenticated USING (true);
CREATE POLICY "form_versions_admin_write" ON public.form_versions FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "form_versions_admin_update" ON public.form_versions FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "form_versions_admin_delete" ON public.form_versions FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "game_modes_read" ON public.game_modes FOR SELECT TO authenticated USING (true);
CREATE POLICY "game_modes_admin_write" ON public.game_modes FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "game_modes_admin_update" ON public.game_modes FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "game_modes_admin_delete" ON public.game_modes FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "game_themes_read" ON public.game_themes FOR SELECT TO authenticated USING (true);
CREATE POLICY "game_themes_admin_write" ON public.game_themes FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "game_themes_admin_update" ON public.game_themes FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "game_themes_admin_delete" ON public.game_themes FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "generated_goal_targets_read" ON public.generated_goal_targets FOR SELECT TO authenticated USING (true);
CREATE POLICY "generated_goal_targets_admin_write" ON public.generated_goal_targets FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "generated_goal_targets_admin_update" ON public.generated_goal_targets FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "generated_goal_targets_admin_delete" ON public.generated_goal_targets FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "goal_intervention_links_read" ON public.goal_intervention_links FOR SELECT TO authenticated USING (true);
CREATE POLICY "goal_intervention_links_admin_write" ON public.goal_intervention_links FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "goal_intervention_links_admin_update" ON public.goal_intervention_links FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "goal_intervention_links_admin_delete" ON public.goal_intervention_links FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "library_crosswalk_rules_read" ON public.library_crosswalk_rules FOR SELECT TO authenticated USING (true);
CREATE POLICY "library_crosswalk_rules_admin_write" ON public.library_crosswalk_rules FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "library_crosswalk_rules_admin_update" ON public.library_crosswalk_rules FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "library_crosswalk_rules_admin_delete" ON public.library_crosswalk_rules FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "library_domains_read" ON public.library_domains FOR SELECT TO authenticated USING (true);
CREATE POLICY "library_domains_admin_write" ON public.library_domains FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "library_domains_admin_update" ON public.library_domains FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "library_domains_admin_delete" ON public.library_domains FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "library_goal_bank_read" ON public.library_goal_bank FOR SELECT TO authenticated USING (true);
CREATE POLICY "library_goal_bank_admin_write" ON public.library_goal_bank FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "library_goal_bank_admin_update" ON public.library_goal_bank FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "library_goal_bank_admin_delete" ON public.library_goal_bank FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "library_goal_objectives_read" ON public.library_goal_objectives FOR SELECT TO authenticated USING (true);
CREATE POLICY "library_goal_objectives_admin_write" ON public.library_goal_objectives FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "library_goal_objectives_admin_update" ON public.library_goal_objectives FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "library_goal_objectives_admin_delete" ON public.library_goal_objectives FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "library_subdomains_read" ON public.library_subdomains FOR SELECT TO authenticated USING (true);
CREATE POLICY "library_subdomains_admin_write" ON public.library_subdomains FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "library_subdomains_admin_update" ON public.library_subdomains FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "library_subdomains_admin_delete" ON public.library_subdomains FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "mtss_escalation_rules_read" ON public.mtss_escalation_rules FOR SELECT TO authenticated USING (true);
CREATE POLICY "mtss_escalation_rules_admin_write" ON public.mtss_escalation_rules FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "mtss_escalation_rules_admin_update" ON public.mtss_escalation_rules FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "mtss_escalation_rules_admin_delete" ON public.mtss_escalation_rules FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "notification_dispatch_queue_read" ON public.notification_dispatch_queue FOR SELECT TO authenticated USING (true);
CREATE POLICY "notification_dispatch_queue_admin_write" ON public.notification_dispatch_queue FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "notification_dispatch_queue_admin_update" ON public.notification_dispatch_queue FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "notification_dispatch_queue_admin_delete" ON public.notification_dispatch_queue FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "notification_events_read" ON public.notification_events FOR SELECT TO authenticated USING (true);
CREATE POLICY "notification_events_admin_write" ON public.notification_events FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "notification_events_admin_update" ON public.notification_events FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "notification_events_admin_delete" ON public.notification_events FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "notification_providers_read" ON public.notification_providers FOR SELECT TO authenticated USING (true);
CREATE POLICY "notification_providers_admin_write" ON public.notification_providers FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "notification_providers_admin_update" ON public.notification_providers FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "notification_providers_admin_delete" ON public.notification_providers FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "package_definition_forms_read" ON public.package_definition_forms FOR SELECT TO authenticated USING (true);
CREATE POLICY "package_definition_forms_admin_write" ON public.package_definition_forms FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "package_definition_forms_admin_update" ON public.package_definition_forms FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "package_definition_forms_admin_delete" ON public.package_definition_forms FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "package_definitions_read" ON public.package_definitions FOR SELECT TO authenticated USING (true);
CREATE POLICY "package_definitions_admin_write" ON public.package_definitions FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "package_definitions_admin_update" ON public.package_definitions FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "package_definitions_admin_delete" ON public.package_definitions FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "parent_question_replies_read" ON public.parent_question_replies FOR SELECT TO authenticated USING (true);
CREATE POLICY "parent_question_replies_admin_write" ON public.parent_question_replies FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "parent_question_replies_admin_update" ON public.parent_question_replies FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "parent_question_replies_admin_delete" ON public.parent_question_replies FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "parent_report_profile_rules_read" ON public.parent_report_profile_rules FOR SELECT TO authenticated USING (true);
CREATE POLICY "parent_report_profile_rules_admin_write" ON public.parent_report_profile_rules FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "parent_report_profile_rules_admin_update" ON public.parent_report_profile_rules FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "parent_report_profile_rules_admin_delete" ON public.parent_report_profile_rules FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "parent_report_profiles_read" ON public.parent_report_profiles FOR SELECT TO authenticated USING (true);
CREATE POLICY "parent_report_profiles_admin_write" ON public.parent_report_profiles FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "parent_report_profiles_admin_update" ON public.parent_report_profiles FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "parent_report_profiles_admin_delete" ON public.parent_report_profiles FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "profile_pending_reviews_read" ON public.profile_pending_reviews FOR SELECT TO authenticated USING (true);
CREATE POLICY "profile_pending_reviews_admin_write" ON public.profile_pending_reviews FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "profile_pending_reviews_admin_update" ON public.profile_pending_reviews FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "profile_pending_reviews_admin_delete" ON public.profile_pending_reviews FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "profile_update_log_read" ON public.profile_update_log FOR SELECT TO authenticated USING (true);
CREATE POLICY "profile_update_log_admin_write" ON public.profile_update_log FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "profile_update_log_admin_update" ON public.profile_update_log FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "profile_update_log_admin_delete" ON public.profile_update_log FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "reinforcement_templates_read" ON public.reinforcement_templates FOR SELECT TO authenticated USING (true);
CREATE POLICY "reinforcement_templates_admin_write" ON public.reinforcement_templates FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "reinforcement_templates_admin_update" ON public.reinforcement_templates FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "reinforcement_templates_admin_delete" ON public.reinforcement_templates FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "replacement_behavior_library_read" ON public.replacement_behavior_library FOR SELECT TO authenticated USING (true);
CREATE POLICY "replacement_behavior_library_admin_write" ON public.replacement_behavior_library FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "replacement_behavior_library_admin_update" ON public.replacement_behavior_library FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "replacement_behavior_library_admin_delete" ON public.replacement_behavior_library FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "report_definitions_read" ON public.report_definitions FOR SELECT TO authenticated USING (true);
CREATE POLICY "report_definitions_admin_write" ON public.report_definitions FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "report_definitions_admin_update" ON public.report_definitions FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "report_definitions_admin_delete" ON public.report_definitions FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "report_exports_read" ON public.report_exports FOR SELECT TO authenticated USING (true);
CREATE POLICY "report_exports_admin_write" ON public.report_exports FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "report_exports_admin_update" ON public.report_exports FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "report_exports_admin_delete" ON public.report_exports FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "report_generation_events_read" ON public.report_generation_events FOR SELECT TO authenticated USING (true);
CREATE POLICY "report_generation_events_admin_write" ON public.report_generation_events FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "report_generation_events_admin_update" ON public.report_generation_events FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "report_generation_events_admin_delete" ON public.report_generation_events FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "reporting_snapshots_read" ON public.reporting_snapshots FOR SELECT TO authenticated USING (true);
CREATE POLICY "reporting_snapshots_admin_write" ON public.reporting_snapshots FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "reporting_snapshots_admin_update" ON public.reporting_snapshots FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "reporting_snapshots_admin_delete" ON public.reporting_snapshots FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "school_culture_prompts_read" ON public.school_culture_prompts FOR SELECT TO authenticated USING (true);
CREATE POLICY "school_culture_prompts_admin_write" ON public.school_culture_prompts FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "school_culture_prompts_admin_update" ON public.school_culture_prompts FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "school_culture_prompts_admin_delete" ON public.school_culture_prompts FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "school_leaderboards_read" ON public.school_leaderboards FOR SELECT TO authenticated USING (true);
CREATE POLICY "school_leaderboards_admin_write" ON public.school_leaderboards FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "school_leaderboards_admin_update" ON public.school_leaderboards FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "school_leaderboards_admin_delete" ON public.school_leaderboards FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "socially_savvy_benchmark_steps_read" ON public.socially_savvy_benchmark_steps FOR SELECT TO authenticated USING (true);
CREATE POLICY "socially_savvy_benchmark_steps_admin_write" ON public.socially_savvy_benchmark_steps FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "socially_savvy_benchmark_steps_admin_update" ON public.socially_savvy_benchmark_steps FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "socially_savvy_benchmark_steps_admin_delete" ON public.socially_savvy_benchmark_steps FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "socially_savvy_objectives_read" ON public.socially_savvy_objectives FOR SELECT TO authenticated USING (true);
CREATE POLICY "socially_savvy_objectives_admin_write" ON public.socially_savvy_objectives FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "socially_savvy_objectives_admin_update" ON public.socially_savvy_objectives FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "socially_savvy_objectives_admin_delete" ON public.socially_savvy_objectives FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "socially_savvy_programs_read" ON public.socially_savvy_programs FOR SELECT TO authenticated USING (true);
CREATE POLICY "socially_savvy_programs_admin_write" ON public.socially_savvy_programs FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "socially_savvy_programs_admin_update" ON public.socially_savvy_programs FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "socially_savvy_programs_admin_delete" ON public.socially_savvy_programs FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "sponsor_contributions_read" ON public.sponsor_contributions FOR SELECT TO authenticated USING (true);
CREATE POLICY "sponsor_contributions_admin_write" ON public.sponsor_contributions FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "sponsor_contributions_admin_update" ON public.sponsor_contributions FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "sponsor_contributions_admin_delete" ON public.sponsor_contributions FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "sponsored_rewards_read" ON public.sponsored_rewards FOR SELECT TO authenticated USING (true);
CREATE POLICY "sponsored_rewards_admin_write" ON public.sponsored_rewards FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "sponsored_rewards_admin_update" ON public.sponsored_rewards FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "sponsored_rewards_admin_delete" ON public.sponsored_rewards FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "sponsors_read" ON public.sponsors FOR SELECT TO authenticated USING (true);
CREATE POLICY "sponsors_admin_write" ON public.sponsors FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "sponsors_admin_update" ON public.sponsors FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "sponsors_admin_delete" ON public.sponsors FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "supervisor_visibility_rules_read" ON public.supervisor_visibility_rules FOR SELECT TO authenticated USING (true);
CREATE POLICY "supervisor_visibility_rules_admin_write" ON public.supervisor_visibility_rules FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "supervisor_visibility_rules_admin_update" ON public.supervisor_visibility_rules FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "supervisor_visibility_rules_admin_delete" ON public.supervisor_visibility_rules FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "unlock_catalog_read" ON public.unlock_catalog FOR SELECT TO authenticated USING (true);
CREATE POLICY "unlock_catalog_admin_write" ON public.unlock_catalog FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "unlock_catalog_admin_update" ON public.unlock_catalog FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "unlock_catalog_admin_delete" ON public.unlock_catalog FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "vineland_age_bands_read" ON public.vineland_age_bands FOR SELECT TO authenticated USING (true);
CREATE POLICY "vineland_age_bands_admin_write" ON public.vineland_age_bands FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "vineland_age_bands_admin_update" ON public.vineland_age_bands FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "vineland_age_bands_admin_delete" ON public.vineland_age_bands FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "vineland_domains_read" ON public.vineland_domains FOR SELECT TO authenticated USING (true);
CREATE POLICY "vineland_domains_admin_write" ON public.vineland_domains FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "vineland_domains_admin_update" ON public.vineland_domains FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "vineland_domains_admin_delete" ON public.vineland_domains FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "vineland_forms_read" ON public.vineland_forms FOR SELECT TO authenticated USING (true);
CREATE POLICY "vineland_forms_admin_write" ON public.vineland_forms FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "vineland_forms_admin_update" ON public.vineland_forms FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "vineland_forms_admin_delete" ON public.vineland_forms FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "vineland_norm_lookup_composites_read" ON public.vineland_norm_lookup_composites FOR SELECT TO authenticated USING (true);
CREATE POLICY "vineland_norm_lookup_composites_admin_write" ON public.vineland_norm_lookup_composites FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "vineland_norm_lookup_composites_admin_update" ON public.vineland_norm_lookup_composites FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "vineland_norm_lookup_composites_admin_delete" ON public.vineland_norm_lookup_composites FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "vineland_norm_lookup_domains_read" ON public.vineland_norm_lookup_domains FOR SELECT TO authenticated USING (true);
CREATE POLICY "vineland_norm_lookup_domains_admin_write" ON public.vineland_norm_lookup_domains FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "vineland_norm_lookup_domains_admin_update" ON public.vineland_norm_lookup_domains FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "vineland_norm_lookup_domains_admin_delete" ON public.vineland_norm_lookup_domains FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "vineland_norm_lookup_subdomains_read" ON public.vineland_norm_lookup_subdomains FOR SELECT TO authenticated USING (true);
CREATE POLICY "vineland_norm_lookup_subdomains_admin_write" ON public.vineland_norm_lookup_subdomains FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "vineland_norm_lookup_subdomains_admin_update" ON public.vineland_norm_lookup_subdomains FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "vineland_norm_lookup_subdomains_admin_delete" ON public.vineland_norm_lookup_subdomains FOR DELETE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "vineland_subdomains_read" ON public.vineland_subdomains FOR SELECT TO authenticated USING (true);
CREATE POLICY "vineland_subdomains_admin_write" ON public.vineland_subdomains FOR INSERT TO authenticated WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "vineland_subdomains_admin_update" ON public.vineland_subdomains FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "vineland_subdomains_admin_delete" ON public.vineland_subdomains FOR DELETE TO authenticated USING (is_admin(auth.uid()));
