-- Batch 07: Transitions, Attendance, Work Completion & School Routines (Items 91-105)
INSERT INTO public.iep_library_items (item_type, title, description, implementation_notes, domains, disability_tags, grade_band, setting_tags, topics, contraindications, idea_compliance_level, export_language, status)
VALUES
  ('accommodation', 'Visual Daily Schedule', 'Student is provided a visual schedule outlining daily routines and transitions.', '["Review schedule daily", "Update schedule when changes occur"]'::jsonb, ARRAY['transitions', 'attention_executive_function'], ARRAY['autism', 'adhd'], ARRAY['preschool', 'elementary', 'middle_school'], ARRAY['general_ed'], ARRAY['predictability'], ARRAY[]::text[], 'safe', '{"iep": "Use of a visual daily schedule to support routines and transitions.", "parent": "Your child may use a visual schedule to understand their daily routine."}'::jsonb, 'active'),
  ('accommodation', 'Advance Notice of Schedule Changes', 'Student is notified in advance of changes to routine or schedule.', '["Provide verbal and visual notice", "Allow time for adjustment"]'::jsonb, ARRAY['transitions', 'anxiety'], ARRAY['autism', 'anxiety'], ARRAY['preschool', 'elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['schedule_changes'], ARRAY[]::text[], 'safe', '{"iep": "Advance notice provided for changes to routine or schedule.", "parent": "Your child will be told ahead of time if routines change."}'::jsonb, 'active'),
  ('accommodation', 'Task Chunking', 'Assignments are broken into smaller, manageable steps.', '["Provide one step at a time", "Use checklists when appropriate"]'::jsonb, ARRAY['attention_executive_function', 'academics'], ARRAY['adhd', 'specific_learning_disability'], ARRAY['elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['task_completion'], ARRAY[]::text[], 'safe', '{"iep": "Assignments broken into smaller steps to support task completion.", "parent": "Work may be divided into smaller parts to help your child complete tasks."}'::jsonb, 'active'),
  ('accommodation', 'Extended Time for Assignments', 'Student is provided additional time to complete assignments as needed.', '["Clarify which assignments qualify", "Coordinate deadlines across classes"]'::jsonb, ARRAY['academics', 'attention_executive_function'], ARRAY['adhd', 'specific_learning_disability'], ARRAY['elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['work_completion'], ARRAY['Avoid indefinite extensions without monitoring'], 'safe', '{"iep": "Additional time provided for assignment completion as needed.", "parent": "Your child may have extra time to finish assignments."}'::jsonb, 'active'),
  ('accommodation', 'Homework Reduction (Non-Essential Items)', 'Homework load is reduced by removing non-essential or repetitive tasks.', '["Maintain instructional objectives", "Focus on mastery rather than volume"]'::jsonb, ARRAY['academics'], ARRAY['adhd', 'anxiety'], ARRAY['elementary', 'middle_school'], ARRAY['general_ed'], ARRAY['homework'], ARRAY['Ensure exposure to core content'], 'safe', '{"iep": "Reduction of homework by removing non-essential tasks.", "parent": "Your child may have less homework while still learning required skills."}'::jsonb, 'active'),
  ('accommodation', 'Assignment Checklists', 'Checklists are provided to help the student track and complete assignments.', '["Teach how to use checklist", "Review checklist regularly"]'::jsonb, ARRAY['attention_executive_function'], ARRAY['adhd', 'autism'], ARRAY['elementary', 'middle_school'], ARRAY['general_ed'], ARRAY['organization'], ARRAY[]::text[], 'safe', '{"iep": "Use of checklists to support assignment completion and organization.", "parent": "Your child may use checklists to keep track of their work."}'::jsonb, 'active'),
  ('accommodation', 'Designated Work Completion Time', 'Student is provided structured time during the school day to complete assignments.', '["Identify optimal time of day", "Provide minimal distractions"]'::jsonb, ARRAY['academics', 'attention_executive_function'], ARRAY['adhd'], ARRAY['elementary', 'middle_school', 'high_school'], ARRAY['general_ed', 'resource_room'], ARRAY['work_completion'], ARRAY[]::text[], 'safe', '{"iep": "Designated time during the school day for assignment completion.", "parent": "Your child may have time at school to work on assignments."}'::jsonb, 'active'),
  ('accommodation', 'Attendance Flexibility for Medical Needs', 'Attendance expectations are adjusted due to documented medical needs.', '["Coordinate with medical documentation", "Provide make-up work opportunities"]'::jsonb, ARRAY['attendance', 'health_medical'], ARRAY['other_health_impairment', '504_only'], ARRAY['elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['attendance_support'], ARRAY['Requires documentation'], 'safe', '{"iep": "Attendance flexibility provided due to medical needs.", "parent": "Attendance expectations may be adjusted for health-related reasons."}'::jsonb, 'active'),
  ('accommodation', 'Late Arrival / Early Dismissal Support', 'Student is supported during late arrival or early dismissal as needed.', '["Coordinate transitions", "Ensure access to missed instruction"]'::jsonb, ARRAY['attendance', 'transitions'], ARRAY['other_health_impairment', '504_only'], ARRAY['middle_school', 'high_school'], ARRAY['transitions'], ARRAY['schedule_flexibility'], ARRAY[]::text[], 'safe', '{"iep": "Support provided for late arrival or early dismissal as needed.", "parent": "Your child may arrive late or leave early with support as needed."}'::jsonb, 'active'),
  ('accommodation', 'Study Skills Instruction', 'Instruction is provided to develop organization, planning, and study strategies.', '["Teach strategies explicitly", "Practice across subjects"]'::jsonb, ARRAY['attention_executive_function', 'academics'], ARRAY['adhd', 'specific_learning_disability'], ARRAY['middle_school', 'high_school'], ARRAY['general_ed', 'resource_room'], ARRAY['study_skills'], ARRAY[]::text[], 'safe', '{"iep": "Instruction in study skills to support organization and learning.", "parent": "Your child may receive help learning how to study and stay organized."}'::jsonb, 'active'),
  ('accommodation', 'Classroom Entry and Exit Routine', 'Clear routines are established for entering and exiting the classroom.', '["Teach routines explicitly", "Reinforce consistency"]'::jsonb, ARRAY['transitions', 'behavior'], ARRAY['autism', 'adhd'], ARRAY['preschool', 'elementary'], ARRAY['general_ed'], ARRAY['routines'], ARRAY[]::text[], 'safe', '{"iep": "Established routines for classroom entry and exit.", "parent": "Your child will follow clear routines when entering and leaving class."}'::jsonb, 'active'),
  ('accommodation', 'Transition Support Person', 'A designated staff member supports the student during challenging transitions.', '["Identify specific transitions", "Fade support when appropriate"]'::jsonb, ARRAY['transitions', 'behavior'], ARRAY['autism', 'emotional_disturbance'], ARRAY['elementary', 'middle_school'], ARRAY['transitions'], ARRAY['transition_support'], ARRAY['Avoid long-term dependence without skill-building'], 'safe', '{"iep": "Designated staff support during challenging transitions.", "parent": "A staff member may help your child during difficult transitions."}'::jsonb, 'active'),
  ('accommodation', 'Self-Monitoring Tools', 'Student uses tools to monitor their own behavior, attention, or work completion.', '["Teach how to self-monitor", "Review data with staff"]'::jsonb, ARRAY['attention_executive_function', 'behavior'], ARRAY['adhd', 'autism'], ARRAY['elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['self_management'], ARRAY[]::text[], 'safe', '{"iep": "Use of self-monitoring tools to support independence.", "parent": "Your child may use tools to track their own behavior or work."}'::jsonb, 'active'),
  ('accommodation', 'Reduced Course Load (Secondary)', 'Student''s course load is reduced to support success while maintaining progress toward graduation.', '["Coordinate with counseling staff", "Monitor impact on graduation requirements"]'::jsonb, ARRAY['academics', 'attendance'], ARRAY['other_health_impairment', 'anxiety'], ARRAY['high_school'], ARRAY['general_ed'], ARRAY['secondary_support'], ARRAY['Requires team and counseling approval'], 'caution', '{"iep": "Reduced course load implemented to support academic success.", "parent": "Your child may take fewer classes to help manage workload."}'::jsonb, 'active'),
  ('accommodation', 'Post-Secondary Transition Planning Support', 'Student receives support related to post-secondary goals such as college, employment, or independent living.', '["Align supports to transition goals", "Coordinate with transition services"]'::jsonb, ARRAY['transition_planning'], ARRAY['intellectual_disability', 'other_health_impairment'], ARRAY['high_school'], ARRAY['general_ed'], ARRAY['post_secondary'], ARRAY[]::text[], 'safe', '{"iep": "Support provided for post-secondary transition planning.", "parent": "Your child will receive help planning for life after high school."}'::jsonb, 'active');

-- Batch 08: Executive Function, Organization, Memory & Assistive Technology (Items 106-120)
INSERT INTO public.iep_library_items (item_type, title, description, implementation_notes, domains, disability_tags, grade_band, setting_tags, topics, contraindications, idea_compliance_level, export_language, status)
VALUES
  ('accommodation', 'Executive Function Coaching', 'Student receives direct support to develop planning, organization, and task initiation skills.', '["Use explicit instruction and modeling", "Practice skills across settings"]'::jsonb, ARRAY['attention_executive_function'], ARRAY['adhd', 'autism'], ARRAY['elementary', 'middle_school', 'high_school'], ARRAY['general_ed', 'resource_room'], ARRAY['planning', 'organization'], ARRAY[]::text[], 'safe', '{"iep": "Executive function coaching provided to support planning and organization skills.", "parent": "Your child may receive help learning how to plan and organize tasks."}'::jsonb, 'active'),
  ('accommodation', 'Daily Planner or Agenda Support', 'Student uses a planner or agenda with adult support to track assignments and responsibilities.', '["Check planner daily", "Teach how to record assignments accurately"]'::jsonb, ARRAY['attention_executive_function'], ARRAY['adhd'], ARRAY['elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['organization', 'time_management'], ARRAY[]::text[], 'safe', '{"iep": "Use of a daily planner or agenda with support to track assignments.", "parent": "Your child may use a planner to keep track of schoolwork."}'::jsonb, 'active'),
  ('accommodation', 'Color-Coded Materials System', 'Color coding is used for subjects or materials to improve organization.', '["Assign consistent colors by subject", "Teach system explicitly"]'::jsonb, ARRAY['attention_executive_function'], ARRAY['adhd', 'specific_learning_disability'], ARRAY['elementary', 'middle_school'], ARRAY['general_ed'], ARRAY['organization'], ARRAY[]::text[], 'safe', '{"iep": "Use of a color-coded system to support organization of materials.", "parent": "Your child may use colors to help organize school materials."}'::jsonb, 'active'),
  ('accommodation', 'Visual Timers', 'Visual timers are used to support time awareness and task completion.', '["Set clear expectations for task duration", "Pair with verbal reminders"]'::jsonb, ARRAY['attention_executive_function'], ARRAY['adhd', 'autism'], ARRAY['preschool', 'elementary', 'middle_school'], ARRAY['general_ed'], ARRAY['time_management'], ARRAY[]::text[], 'safe', '{"iep": "Use of visual timers to support time management and task completion.", "parent": "Your child may use a timer to understand how much time they have."}'::jsonb, 'active'),
  ('accommodation', 'Assignment Due Date Reminders', 'Student receives reminders about upcoming assignment due dates.', '["Use verbal, visual, or digital reminders", "Coordinate across classes"]'::jsonb, ARRAY['attention_executive_function', 'academics'], ARRAY['adhd'], ARRAY['elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['memory_support'], ARRAY[]::text[], 'safe', '{"iep": "Provision of reminders for upcoming assignment due dates.", "parent": "Your child may receive reminders to help remember when work is due."}'::jsonb, 'active'),
  ('accommodation', 'Written Task Directions Checklist', 'Written checklists outline steps required to complete tasks.', '["Break tasks into observable steps", "Fade checklist support over time"]'::jsonb, ARRAY['attention_executive_function', 'communication'], ARRAY['adhd', 'autism'], ARRAY['elementary', 'middle_school'], ARRAY['general_ed'], ARRAY['task_completion'], ARRAY[]::text[], 'safe', '{"iep": "Written task checklists provided to support task completion.", "parent": "Your child may use checklists to know what steps to follow."}'::jsonb, 'active'),
  ('accommodation', 'Assistive Technology for Organization', 'Digital tools or apps are used to support organization and task tracking.', '["Select age-appropriate tools", "Provide instruction in use"]'::jsonb, ARRAY['assistive_technology', 'attention_executive_function'], ARRAY['adhd', 'specific_learning_disability'], ARRAY['middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['assistive_tech'], ARRAY['Ensure compliance with school technology policies'], 'safe', '{"iep": "Use of assistive technology to support organization and task management.", "parent": "Your child may use technology tools to stay organized."}'::jsonb, 'active'),
  ('accommodation', 'Memory Aids and Cue Cards', 'Cue cards or memory aids are used to support recall of key information.', '["Limit information per card", "Teach how to reference aids"]'::jsonb, ARRAY['memory', 'communication'], ARRAY['specific_learning_disability'], ARRAY['elementary', 'middle_school'], ARRAY['general_ed'], ARRAY['memory_support'], ARRAY[]::text[], 'safe', '{"iep": "Use of memory aids or cue cards to support recall.", "parent": "Your child may use cards or notes to help remember information."}'::jsonb, 'active'),
  ('accommodation', 'Chunked Time Blocks for Work', 'Work time is divided into short, structured intervals.', '["Include brief breaks between work periods", "Increase duration gradually"]'::jsonb, ARRAY['attention_executive_function'], ARRAY['adhd', 'anxiety'], ARRAY['elementary', 'middle_school'], ARRAY['general_ed'], ARRAY['sustained_attention'], ARRAY[]::text[], 'safe', '{"iep": "Use of structured work periods with breaks to support attention.", "parent": "Your child may work in short periods with breaks in between."}'::jsonb, 'active'),
  ('accommodation', 'Reduced Multi-Step Directions', 'Multi-step directions are reduced or provided one step at a time.', '["Confirm understanding after each step", "Pair with visuals when possible"]'::jsonb, ARRAY['communication', 'attention_executive_function'], ARRAY['adhd', 'autism'], ARRAY['preschool', 'elementary'], ARRAY['general_ed'], ARRAY['directions'], ARRAY[]::text[], 'safe', '{"iep": "Reduction of multi-step directions to support comprehension.", "parent": "Directions may be given one step at a time to help your child understand."}'::jsonb, 'active'),
  ('accommodation', 'Organizational Check-In', 'Student participates in regular check-ins to review organization of materials.', '["Schedule weekly or biweekly check-ins", "Teach organization strategies"]'::jsonb, ARRAY['attention_executive_function'], ARRAY['adhd'], ARRAY['elementary', 'middle_school'], ARRAY['general_ed'], ARRAY['organization'], ARRAY[]::text[], 'safe', '{"iep": "Regular organizational check-ins to support material management.", "parent": "Your child may meet with staff to organize school materials."}'::jsonb, 'active'),
  ('accommodation', 'Digital Copies of Materials', 'Student is provided digital copies of instructional materials.', '["Ensure accessibility features are enabled", "Organize files clearly"]'::jsonb, ARRAY['assistive_technology', 'academics'], ARRAY['specific_learning_disability', 'other_health_impairment'], ARRAY['middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['access_to_materials'], ARRAY[]::text[], 'safe', '{"iep": "Provision of digital copies of instructional materials.", "parent": "Your child may receive school materials in digital form."}'::jsonb, 'active'),
  ('accommodation', 'Assistive Technology Training', 'Student receives instruction on how to use assistive technology tools effectively.', '["Provide ongoing training", "Monitor effective use"]'::jsonb, ARRAY['assistive_technology'], ARRAY['specific_learning_disability', 'autism'], ARRAY['elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['assistive_tech_training'], ARRAY[]::text[], 'safe', '{"iep": "Training provided to support effective use of assistive technology.", "parent": "Your child will be taught how to use helpful technology tools."}'::jsonb, 'active'),
  ('accommodation', 'Environmental Organization Supports', 'Classroom environment includes labeled areas and storage to support organization.', '["Use clear labels and visuals", "Maintain consistency"]'::jsonb, ARRAY['environmental_access', 'attention_executive_function'], ARRAY['autism', 'adhd'], ARRAY['preschool', 'elementary'], ARRAY['general_ed'], ARRAY['environmental_structure'], ARRAY[]::text[], 'safe', '{"iep": "Environmental organization supports implemented in the classroom.", "parent": "The classroom may be organized with labels to help your child stay organized."}'::jsonb, 'active'),
  ('accommodation', 'Time Management Skill Instruction', 'Direct instruction is provided to build time management skills.', '["Use modeling and practice", "Apply skills to real tasks"]'::jsonb, ARRAY['attention_executive_function'], ARRAY['adhd'], ARRAY['middle_school', 'high_school'], ARRAY['general_ed', 'resource_room'], ARRAY['time_management'], ARRAY[]::text[], 'safe', '{"iep": "Instruction in time management skills to support academic success.", "parent": "Your child may learn strategies to better manage their time."}'::jsonb, 'active');

-- Batch 09: Sensory Regulation, Emotional Regulation & Mental Health Supports (Items 121-135)
INSERT INTO public.iep_library_items (item_type, title, description, implementation_notes, domains, disability_tags, grade_band, setting_tags, topics, contraindications, idea_compliance_level, export_language, status)
VALUES
  ('accommodation', 'Scheduled Sensory Breaks', 'Student is provided scheduled sensory breaks to support regulation and engagement.', '["Schedule breaks proactively", "Fade frequency as regulation skills improve"]'::jsonb, ARRAY['sensory_regulation'], ARRAY['autism', 'adhd'], ARRAY['preschool', 'elementary', 'middle_school'], ARRAY['general_ed'], ARRAY['sensory_support'], ARRAY['Monitor to ensure breaks are not escape-maintained'], 'safe', '{"iep": "Scheduled sensory breaks provided to support regulation.", "parent": "Your child may take planned sensory breaks during the day."}'::jsonb, 'active'),
  ('accommodation', 'Access to Calm Down Area', 'Student may access a designated calm-down area to regulate emotions.', '["Teach expectations for use", "Ensure supervision and time limits"]'::jsonb, ARRAY['emotional_regulation', 'behavior'], ARRAY['autism', 'anxiety', 'emotional_disturbance'], ARRAY['preschool', 'elementary', 'middle_school'], ARRAY['general_ed'], ARRAY['self_regulation'], ARRAY['Avoid isolative or exclusionary use'], 'caution', '{"iep": "Access to a designated area for emotional regulation.", "parent": "Your child may use a calm space to help manage big feelings."}'::jsonb, 'active'),
  ('accommodation', 'Sensory Tools and Equipment', 'Student is provided access to sensory tools (e.g., fidgets, weighted items) as appropriate.', '["Select tools based on sensory needs", "Teach appropriate use"]'::jsonb, ARRAY['sensory_regulation'], ARRAY['autism', 'adhd', 'anxiety'], ARRAY['preschool', 'elementary', 'middle_school'], ARRAY['general_ed'], ARRAY['sensory_input'], ARRAY['Ensure tools do not distract others'], 'safe', '{"iep": "Access to sensory tools to support regulation and attention.", "parent": "Your child may use sensory items to help stay calm and focused."}'::jsonb, 'active'),
  ('accommodation', 'Emotion Identification Instruction', 'Student receives instruction to identify and label emotions.', '["Use visuals and modeling", "Practice during calm moments"]'::jsonb, ARRAY['emotional_regulation', 'social_emotional'], ARRAY['autism', 'emotional_disturbance'], ARRAY['preschool', 'elementary'], ARRAY['general_ed', 'small_group'], ARRAY['emotional_awareness'], ARRAY[]::text[], 'safe', '{"iep": "Instruction provided to support identification and labeling of emotions.", "parent": "Your child may learn to recognize and name their feelings."}'::jsonb, 'active'),
  ('accommodation', 'Coping Strategy Instruction', 'Student is taught coping strategies to manage stress and emotional responses.', '["Teach strategies explicitly", "Practice across settings"]'::jsonb, ARRAY['emotional_regulation', 'mental_health'], ARRAY['anxiety', 'emotional_disturbance'], ARRAY['elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['coping_skills'], ARRAY[]::text[], 'safe', '{"iep": "Instruction in coping strategies to support emotional regulation.", "parent": "Your child may learn ways to cope with stress or anxiety."}'::jsonb, 'active'),
  ('accommodation', 'Mindfulness or Relaxation Activities', 'Mindfulness or relaxation activities are incorporated to support regulation.', '["Use short, age-appropriate activities", "Offer participation as supportive, not punitive"]'::jsonb, ARRAY['emotional_regulation', 'mental_health'], ARRAY['anxiety', 'adhd'], ARRAY['elementary', 'middle_school'], ARRAY['general_ed'], ARRAY['relaxation'], ARRAY[]::text[], 'safe', '{"iep": "Use of mindfulness or relaxation activities to support regulation.", "parent": "Your child may practice calming or relaxation activities at school."}'::jsonb, 'active'),
  ('accommodation', 'Counseling Check-Ins', 'Student receives periodic check-ins with school counseling staff.', '["Coordinate schedule with academics", "Focus on emotional support and problem-solving"]'::jsonb, ARRAY['mental_health'], ARRAY['anxiety', 'emotional_disturbance'], ARRAY['elementary', 'middle_school', 'high_school'], ARRAY['counseling'], ARRAY['emotional_support'], ARRAY[]::text[], 'safe', '{"iep": "Regular counseling check-ins to support emotional well-being.", "parent": "Your child may meet with a counselor for emotional support."}'::jsonb, 'active'),
  ('accommodation', 'Safe Person Identification', 'Student identifies a trusted adult they can seek out when experiencing emotional distress.', '["Ensure staff availability", "Teach when and how to seek support"]'::jsonb, ARRAY['emotional_regulation', 'safety'], ARRAY['anxiety', 'autism'], ARRAY['preschool', 'elementary', 'middle_school'], ARRAY['general_ed'], ARRAY['help_seeking'], ARRAY[]::text[], 'safe', '{"iep": "Identification of a trusted adult for emotional support.", "parent": "Your child will know which adult to go to if they feel overwhelmed."}'::jsonb, 'active'),
  ('accommodation', 'Reduced Exposure During High-Stress Activities', 'Student participation is adjusted during high-stress activities when appropriate.', '["Identify triggers", "Gradually increase exposure as tolerated"]'::jsonb, ARRAY['mental_health', 'emotional_regulation'], ARRAY['anxiety'], ARRAY['elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['stress_management'], ARRAY['Avoid permanent avoidance without skill-building'], 'caution', '{"iep": "Adjusted participation during high-stress activities as needed.", "parent": "Some activities may be adjusted to reduce stress for your child."}'::jsonb, 'active'),
  ('accommodation', 'Behavior Rating Scales for Emotional Monitoring', 'Behavior or mood rating tools are used to monitor emotional regulation.', '["Use developmentally appropriate scales", "Review data regularly"]'::jsonb, ARRAY['mental_health', 'behavior'], ARRAY['emotional_disturbance', 'anxiety'], ARRAY['elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['progress_monitoring'], ARRAY[]::text[], 'safe', '{"iep": "Use of rating tools to monitor emotional regulation and behavior.", "parent": "The school may track emotional well-being using simple rating tools."}'::jsonb, 'active'),
  ('accommodation', 'Calming Visual Supports', 'Visual supports (e.g., calm-down posters, emotion charts) are used to support regulation.', '["Keep visuals accessible", "Teach meaning of visuals"]'::jsonb, ARRAY['sensory_regulation', 'emotional_regulation'], ARRAY['autism', 'anxiety'], ARRAY['preschool', 'elementary'], ARRAY['general_ed'], ARRAY['visual_supports'], ARRAY[]::text[], 'safe', '{"iep": "Use of calming visual supports to aid emotional regulation.", "parent": "Your child may see pictures or charts that help with calming down."}'::jsonb, 'active'),
  ('accommodation', 'Break Card or Signal', 'Student uses a visual or verbal signal to request a break when overwhelmed.', '["Teach appropriate use", "Honor requests within set parameters"]'::jsonb, ARRAY['emotional_regulation', 'communication'], ARRAY['autism', 'anxiety'], ARRAY['preschool', 'elementary', 'middle_school'], ARRAY['general_ed'], ARRAY['self_advocacy'], ARRAY['Ensure break requests are time-limited'], 'safe', '{"iep": "Use of a break signal to request support during overwhelm.", "parent": "Your child may use a card or signal to ask for a break."}'::jsonb, 'active'),
  ('accommodation', 'Gradual Exposure to Anxiety-Provoking Tasks', 'Tasks that trigger anxiety are introduced gradually with support.', '["Start with low-demand exposure", "Increase demands systematically"]'::jsonb, ARRAY['mental_health'], ARRAY['anxiety'], ARRAY['elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['anxiety_support'], ARRAY['Requires careful monitoring'], 'caution', '{"iep": "Gradual exposure strategies used to support participation in challenging tasks.", "parent": "Your child may slowly practice tasks that feel stressful with support."}'::jsonb, 'active'),
  ('accommodation', 'Crisis Support Protocol', 'A protocol is in place to respond to emotional or mental health crises.', '["Follow district crisis procedures", "Ensure staff training"]'::jsonb, ARRAY['mental_health', 'safety'], ARRAY['emotional_disturbance'], ARRAY['middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['crisis_support'], ARRAY['Must align with district and state policy'], 'caution', '{"iep": "Crisis support procedures implemented to address mental health emergencies.", "parent": "The school has a plan to respond if your child experiences a crisis."}'::jsonb, 'active'),
  ('accommodation', 'Emotional Regulation Goal Alignment', 'Classroom supports are aligned with emotional regulation IEP goals.', '["Ensure consistency across staff", "Review progress regularly"]'::jsonb, ARRAY['emotional_regulation'], ARRAY['autism', 'emotional_disturbance', 'anxiety'], ARRAY['preschool', 'elementary', 'middle_school'], ARRAY['general_ed'], ARRAY['goal_alignment'], ARRAY[]::text[], 'safe', '{"iep": "Classroom supports aligned with emotional regulation goals.", "parent": "School supports will match your child''s emotional goals."}'::jsonb, 'active');