-- Insert batch 03: Communication, Language, Auditory & Visual Access (Items 31-45)
-- and batch 05: Academics: Reading, Writing, Math (Items 61-75)
INSERT INTO public.iep_library_items (item_type, title, description, implementation_notes, domains, disability_tags, grade_band, setting_tags, topics, contraindications, idea_compliance_level, export_language, status)
VALUES
  -- Batch 03: Communication, Language, Auditory & Visual Access
  ('accommodation', 'Simplified Language', 'Instruction and directions are provided using clear, concise, and concrete language.', '["Avoid idioms and abstract phrasing", "Use short sentences", "Confirm understanding after directions"]'::jsonb, ARRAY['communication', 'academics'], ARRAY['autism', 'specific_learning_disability', 'speech_language_impairment'], ARRAY['preschool', 'elementary', 'middle_school'], ARRAY['general_ed', 'small_group'], ARRAY['language_processing'], ARRAY[]::text[], 'safe', '{"iep": "Use of simplified language to support understanding of instruction.", "parent": "Teachers may use clear and simple language to help your child understand directions."}'::jsonb, 'active'),
  
  ('accommodation', 'Repetition and Rephrasing of Instructions', 'Instructions are repeated or rephrased as needed to support comprehension.', '["Rephrase rather than repeat verbatim when needed", "Pair with visual supports when possible"]'::jsonb, ARRAY['communication', 'academics'], ARRAY['adhd', 'autism', 'specific_learning_disability'], ARRAY['preschool', 'elementary', 'middle_school'], ARRAY['general_ed'], ARRAY['directions', 'comprehension'], ARRAY[]::text[], 'safe', '{"iep": "Repetition or rephrasing of directions as needed to support comprehension.", "parent": "Directions may be repeated or said in a different way to help your child understand."}'::jsonb, 'active'),
  
  ('accommodation', 'Visual Supports for Instruction', 'Visual supports such as charts, images, or written cues are used to supplement verbal instruction.', '["Match visuals to student comprehension level", "Use consistent symbols or formats"]'::jsonb, ARRAY['visual_access', 'communication'], ARRAY['autism', 'speech_language_impairment', 'specific_learning_disability'], ARRAY['preschool', 'elementary', 'middle_school'], ARRAY['general_ed', 'small_group'], ARRAY['visual_learning'], ARRAY[]::text[], 'safe', '{"iep": "Use of visual supports to supplement verbal instruction.", "parent": "Your child may see pictures or written cues to help understand lessons."}'::jsonb, 'active'),
  
  ('accommodation', 'Written Directions Provided', 'Directions are provided in written form in addition to verbal instruction.', '["Highlight or bold key steps", "Check readability level"]'::jsonb, ARRAY['communication', 'academics'], ARRAY['adhd', 'specific_learning_disability'], ARRAY['elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['directions', 'memory_support'], ARRAY[]::text[], 'safe', '{"iep": "Provision of written directions in addition to verbal instruction.", "parent": "Directions may be written down so your child can refer back to them."}'::jsonb, 'active'),
  
  ('accommodation', 'Speech-to-Text Technology', 'Student uses speech-to-text technology to support written expression.', '["Provide training on use of technology", "Allow editing time after dictation"]'::jsonb, ARRAY['communication', 'academics_writing'], ARRAY['specific_learning_disability', 'speech_language_impairment'], ARRAY['elementary', 'middle_school', 'high_school'], ARRAY['general_ed', 'testing'], ARRAY['written_expression'], ARRAY['Ensure technology use aligns with assessment guidelines'], 'safe', '{"iep": "Use of speech-to-text technology to support written expression.", "parent": "Your child may speak their ideas and have them turned into written words."}'::jsonb, 'active'),
  
  ('accommodation', 'Text-to-Speech Technology', 'Text-to-speech technology is used to support access to written materials.', '["Use for assignments and assessments when permitted", "Pair with comprehension checks"]'::jsonb, ARRAY['auditory_access', 'academics_reading'], ARRAY['specific_learning_disability', 'speech_language_impairment'], ARRAY['elementary', 'middle_school', 'high_school'], ARRAY['general_ed', 'testing'], ARRAY['reading_access'], ARRAY['Follow assessment accommodation rules'], 'safe', '{"iep": "Use of text-to-speech technology to support access to written materials.", "parent": "Your child may listen to text being read aloud by a device."}'::jsonb, 'active'),
  
  ('accommodation', 'Captioned Videos and Media', 'All instructional videos and media include captions.', '["Ensure captions are accurate", "Provide transcripts when available"]'::jsonb, ARRAY['auditory_access', 'communication'], ARRAY['deaf_hard_of_hearing', 'specific_learning_disability'], ARRAY['elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['media_access'], ARRAY[]::text[], 'safe', '{"iep": "Provision of captioned instructional videos and media.", "parent": "Videos shown in class will include captions."}'::jsonb, 'active'),
  
  ('accommodation', 'Note-Taking Support', 'Student receives assistance with note-taking to support access to instruction.', '["Provide teacher notes or outlines", "Use peer note-sharing when appropriate"]'::jsonb, ARRAY['communication', 'academics'], ARRAY['adhd', 'specific_learning_disability'], ARRAY['middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['note_taking'], ARRAY['Avoid dependence without skill-building'], 'safe', '{"iep": "Provision of note-taking supports to assist with access to instruction.", "parent": "Your child may receive notes or outlines from the teacher."}'::jsonb, 'active'),
  
  ('accommodation', 'Preferential Seating for Auditory Access', 'Student is seated to maximize auditory and visual access to instruction.', '["Seat near primary speaker", "Ensure clear line of sight"]'::jsonb, ARRAY['auditory_access', 'visual_access'], ARRAY['deaf_hard_of_hearing', 'auditory_processing_disorder'], ARRAY['preschool', 'elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['auditory_access'], ARRAY[]::text[], 'safe', '{"iep": "Preferential seating to maximize auditory and visual access to instruction.", "parent": "Your child may sit where they can better see and hear the teacher."}'::jsonb, 'active'),
  
  ('accommodation', 'Check for Attention Before Instruction', 'Staff ensure the student''s attention before providing instruction or directions.', '["Use name or visual cue", "Wait for eye contact or acknowledgment"]'::jsonb, ARRAY['communication', 'attention_executive_function'], ARRAY['adhd', 'autism'], ARRAY['preschool', 'elementary'], ARRAY['general_ed'], ARRAY['attention'], ARRAY[]::text[], 'safe', '{"iep": "Staff will gain the student''s attention before providing instruction.", "parent": "Teachers may make sure your child is paying attention before giving directions."}'::jsonb, 'active'),
  
  ('accommodation', 'Processing Time Allowance', 'Student is given additional time to process information before responding.', '["Pause after asking questions", "Avoid rushing responses"]'::jsonb, ARRAY['communication', 'attention_executive_function'], ARRAY['specific_learning_disability', 'speech_language_impairment'], ARRAY['preschool', 'elementary', 'middle_school'], ARRAY['general_ed'], ARRAY['processing_speed'], ARRAY[]::text[], 'safe', '{"iep": "Additional processing time provided before responses are expected.", "parent": "Your child may be given extra time to think before answering."}'::jsonb, 'active'),
  
  ('accommodation', 'Interpreter Services', 'Provision of interpreting services to support access to instruction.', '["Use qualified interpreters", "Coordinate with instructional pacing"]'::jsonb, ARRAY['communication', 'auditory_access'], ARRAY['deaf_hard_of_hearing'], ARRAY['preschool', 'elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['language_access'], ARRAY[]::text[], 'safe', '{"iep": "Provision of interpreter services to support access to instruction.", "parent": "An interpreter may be provided to help your child understand instruction."}'::jsonb, 'active'),
  
  ('accommodation', 'Assistive Listening Devices', 'Use of assistive listening devices to improve auditory access.', '["Ensure devices are functioning", "Train staff and student on use"]'::jsonb, ARRAY['auditory_access'], ARRAY['deaf_hard_of_hearing'], ARRAY['preschool', 'elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['hearing_support'], ARRAY[]::text[], 'safe', '{"iep": "Use of assistive listening devices to support auditory access.", "parent": "Your child may use equipment to help hear instruction more clearly."}'::jsonb, 'active'),
  
  ('accommodation', 'Graphic Organizers', 'Graphic organizers are used to support comprehension and organization of information.', '["Model how to use organizers", "Align organizer type to task"]'::jsonb, ARRAY['communication', 'academics'], ARRAY['specific_learning_disability', 'adhd'], ARRAY['elementary', 'middle_school'], ARRAY['general_ed'], ARRAY['organization', 'comprehension'], ARRAY[]::text[], 'safe', '{"iep": "Use of graphic organizers to support comprehension and organization.", "parent": "Your child may use charts or diagrams to organize their ideas."}'::jsonb, 'active'),
  
  ('accommodation', 'Alternative Response Formats', 'Student may respond using alternative formats such as oral responses or visuals.', '["Match response format to learning goal", "Ensure alignment with assessment requirements"]'::jsonb, ARRAY['communication', 'testing_assessment'], ARRAY['speech_language_impairment', 'specific_learning_disability'], ARRAY['elementary', 'middle_school', 'high_school'], ARRAY['general_ed', 'testing'], ARRAY['expression'], ARRAY['Follow testing accommodation guidelines'], 'safe', '{"iep": "Alternative response formats may be used to demonstrate knowledge.", "parent": "Your child may show what they know in ways other than writing."}'::jsonb, 'active'),

  -- Batch 05: Academics: Reading, Writing, Math
  ('accommodation', 'Pre-Teaching of Vocabulary', 'Key vocabulary is taught prior to new lessons to support comprehension.', '["Introduce vocabulary before instruction", "Use visuals and examples", "Review words after instruction"]'::jsonb, ARRAY['academics_reading', 'communication'], ARRAY['specific_learning_disability', 'autism', 'speech_language_impairment'], ARRAY['elementary', 'middle_school'], ARRAY['general_ed'], ARRAY['vocabulary', 'comprehension'], ARRAY[]::text[], 'safe', '{"iep": "Pre-teaching of key vocabulary to support comprehension of instruction.", "parent": "Important words may be taught ahead of time to help your child understand lessons."}'::jsonb, 'active'),
  
  ('accommodation', 'Reading Materials at Instructional Level', 'Supplemental reading materials are provided at the student''s instructional reading level.', '["Use alongside grade-level instruction", "Align content to classroom topics"]'::jsonb, ARRAY['academics_reading'], ARRAY['specific_learning_disability', 'intellectual_disability'], ARRAY['elementary', 'middle_school'], ARRAY['general_ed'], ARRAY['reading_access'], ARRAY['Ensure exposure to grade-level content continues'], 'safe', '{"iep": "Supplemental reading materials provided at the student''s instructional level.", "parent": "Your child may read materials that match their reading level to build skills."}'::jsonb, 'active'),
  
  ('accommodation', 'Repeated Reading Opportunities', 'Student practices reading the same text multiple times to build fluency.', '["Use short, meaningful texts", "Track fluency progress"]'::jsonb, ARRAY['academics_reading'], ARRAY['specific_learning_disability'], ARRAY['elementary'], ARRAY['general_ed', 'small_group'], ARRAY['fluency'], ARRAY[]::text[], 'safe', '{"iep": "Repeated reading opportunities to support reading fluency.", "parent": "Your child may practice reading the same passage more than once to build fluency."}'::jsonb, 'active'),
  
  ('accommodation', 'Spelling Aids', 'Access to spelling tools such as word banks, dictionaries, or spell check.', '["Teach how to use tools effectively", "Allow during drafting stages"]'::jsonb, ARRAY['academics_writing'], ARRAY['specific_learning_disability'], ARRAY['elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['spelling'], ARRAY['Follow testing accommodation rules'], 'safe', '{"iep": "Use of spelling aids to support written expression.", "parent": "Your child may use tools to help with spelling when writing."}'::jsonb, 'active'),
  
  ('accommodation', 'Sentence Starters and Writing Frames', 'Sentence starters and structured frames support written expression.', '["Model use during instruction", "Gradually fade supports"]'::jsonb, ARRAY['academics_writing', 'communication'], ARRAY['specific_learning_disability', 'speech_language_impairment'], ARRAY['elementary', 'middle_school'], ARRAY['general_ed'], ARRAY['written_expression'], ARRAY[]::text[], 'safe', '{"iep": "Use of sentence starters or writing frames to support written expression.", "parent": "Your child may be given sentence starters to help begin writing."}'::jsonb, 'active'),
  
  ('accommodation', 'Reduced Copying from Board', 'Student is not required to copy extensive information from the board.', '["Provide printed or digital notes", "Highlight key information"]'::jsonb, ARRAY['academics_writing', 'attention_executive_function'], ARRAY['adhd', 'specific_learning_disability'], ARRAY['elementary', 'middle_school'], ARRAY['general_ed'], ARRAY['written_output'], ARRAY[]::text[], 'safe', '{"iep": "Reduction of copying demands by providing notes or outlines.", "parent": "Your child may receive notes instead of copying everything from the board."}'::jsonb, 'active'),
  
  ('accommodation', 'Graphic Organizers for Writing', 'Graphic organizers are used to plan and structure writing tasks.', '["Choose organizer based on writing type", "Model organizer use"]'::jsonb, ARRAY['academics_writing'], ARRAY['specific_learning_disability', 'adhd'], ARRAY['elementary', 'middle_school'], ARRAY['general_ed'], ARRAY['organization'], ARRAY[]::text[], 'safe', '{"iep": "Use of graphic organizers to support writing structure and organization.", "parent": "Your child may use charts or organizers to plan writing."}'::jsonb, 'active'),
  
  ('accommodation', 'Calculator Use for Computation', 'Student may use a calculator to support math computation when appropriate.', '["Align use with instructional goals", "Do not replace instruction in foundational skills"]'::jsonb, ARRAY['academics_math'], ARRAY['specific_learning_disability'], ARRAY['elementary', 'middle_school', 'high_school'], ARRAY['general_ed', 'testing'], ARRAY['computation'], ARRAY['Follow assessment accommodation guidelines'], 'safe', '{"iep": "Use of a calculator to support math computation as appropriate.", "parent": "Your child may use a calculator to help with math calculations."}'::jsonb, 'active'),
  
  ('accommodation', 'Math Reference Sheets', 'Reference sheets with formulas or steps are provided during math tasks.', '["Limit to essential information", "Teach how to reference effectively"]'::jsonb, ARRAY['academics_math'], ARRAY['specific_learning_disability', 'adhd'], ARRAY['elementary', 'middle_school'], ARRAY['general_ed'], ARRAY['problem_solving'], ARRAY['Follow testing rules'], 'safe', '{"iep": "Provision of math reference sheets to support problem-solving.", "parent": "Your child may use a reference sheet to remember math steps."}'::jsonb, 'active'),
  
  ('accommodation', 'Alternate Demonstration of Knowledge (Academics)', 'Student may demonstrate understanding using alternative formats.', '["Align format to learning objective", "Ensure grading criteria remain consistent"]'::jsonb, ARRAY['academics', 'testing_assessment'], ARRAY['specific_learning_disability', 'speech_language_impairment'], ARRAY['elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['assessment_access'], ARRAY['Follow assessment guidelines'], 'safe', '{"iep": "Alternative formats may be used to demonstrate academic understanding.", "parent": "Your child may show learning in ways other than traditional tests."}'::jsonb, 'active'),
  
  ('accommodation', 'Extra Practice Opportunities', 'Additional practice opportunities are provided to reinforce academic skills.', '["Focus on skill mastery", "Use varied formats"]'::jsonb, ARRAY['academics'], ARRAY['specific_learning_disability', 'intellectual_disability'], ARRAY['elementary', 'middle_school'], ARRAY['general_ed', 'small_group'], ARRAY['skill_mastery'], ARRAY[]::text[], 'safe', '{"iep": "Additional practice opportunities provided to reinforce academic skills.", "parent": "Your child may have extra practice to help build skills."}'::jsonb, 'active'),
  
  ('accommodation', 'Read-Aloud for Word Problems', 'Math word problems are read aloud to support comprehension.', '["Clarify language without explaining the solution", "Ensure consistency across settings"]'::jsonb, ARRAY['academics_math', 'communication'], ARRAY['specific_learning_disability', 'speech_language_impairment'], ARRAY['elementary', 'middle_school'], ARRAY['general_ed', 'testing'], ARRAY['math_language'], ARRAY['Follow testing rules'], 'safe', '{"iep": "Math word problems may be read aloud to support comprehension.", "parent": "Your child may have math problems read aloud to help understand them."}'::jsonb, 'active'),
  
  ('modification', 'Modified Academic Assignments', 'Assignments are modified to align with individualized learning goals.', '["Align modifications with IEP goals", "Document rationale clearly"]'::jsonb, ARRAY['academics'], ARRAY['intellectual_disability'], ARRAY['elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['curriculum_modification'], ARRAY['Requires IEP team agreement'], 'modification', '{"iep": "Academic assignments may be modified to align with individualized goals.", "parent": "Your child''s work may be adjusted to match their learning goals."}'::jsonb, 'active'),
  
  ('modification', 'Alternate Curriculum', 'Student receives instruction using an alternate curriculum aligned to functional or developmental goals.', '["Align curriculum to student needs", "Review placement regularly"]'::jsonb, ARRAY['academics', 'adaptive_functioning'], ARRAY['intellectual_disability'], ARRAY['elementary', 'middle_school', 'high_school'], ARRAY['special_ed'], ARRAY['alternate_standards'], ARRAY['Significant impact on access to general education standards'], 'modification', '{"iep": "Instruction using an alternate curriculum aligned to individualized needs.", "parent": "Your child may use a different curriculum designed for their learning needs."}'::jsonb, 'active'),
  
  ('accommodation', 'Explicit Instruction with Modeling', 'Teacher provides direct instruction with modeling and guided practice.', '["Model each step", "Provide guided practice before independent work"]'::jsonb, ARRAY['academics', 'communication'], ARRAY['specific_learning_disability', 'intellectual_disability'], ARRAY['elementary', 'middle_school'], ARRAY['general_ed', 'small_group'], ARRAY['explicit_instruction'], ARRAY[]::text[], 'safe', '{"iep": "Explicit instruction with modeling to support academic skill development.", "parent": "Teachers may show and practice skills with your child before independent work."}'::jsonb, 'active');