-- Add Batch 01 IEP Library Items (Items 7-15)
INSERT INTO public.iep_library_items (item_type, title, description, implementation_notes, domains, disability_tags, grade_band, setting_tags, topics, contraindications, idea_compliance_level, export_language, source_reference, status) VALUES
('accommodation', 'Visual Timer', 'A visual representation of time to support task completion and transitions.', '["Use a countdown format when possible", "Pair with verbal time warnings (e.g., 5 minutes, 2 minutes)", "Fade support over time if appropriate"]', ARRAY['attention_executive_function', 'transitions'], ARRAY['adhd', 'autism', 'anxiety'], ARRAY['preschool', 'elementary', 'middle_school'], ARRAY['general_ed', 'small_group'], ARRAY['time_management', 'transitions'], ARRAY['May increase anxiety if time pressure is emphasized'], 'safe', '{"iep": "Use of a visual timer to support transitions and task completion.", "parent": "Your child may use a timer to help understand how much time is left."}', ARRAY['IEP/504 Checklist'], 'active'),

('accommodation', 'Step-by-Step Directions', 'Instructions are provided in clear, sequential steps to support understanding and completion.', '["Provide one step at a time if needed", "Use written or visual supports to match verbal directions", "Check for understanding before independent work begins"]', ARRAY['attention_executive_function', 'academics_reading', 'academics_writing', 'academics_math'], ARRAY['adhd', 'autism', 'specific_learning_disability'], ARRAY['elementary', 'middle_school'], ARRAY['general_ed'], ARRAY['task_initiation', 'directions'], '{}', 'safe', '{"iep": "Instructions may be provided in clear, step-by-step format.", "parent": "Directions may be given in smaller steps to help your child understand what to do."}', ARRAY['IEP/504 Checklist'], 'active'),

('accommodation', 'Preferential Testing Location', 'Student completes assessments in a reduced-distraction setting to support performance.', '["Use a quiet room, study carrel, or small group setting", "Maintain test integrity and standard administration requirements"]', ARRAY['testing_assessment'], ARRAY['adhd', 'anxiety', 'autism'], ARRAY['elementary', 'middle_school', 'high_school'], ARRAY['testing'], ARRAY['test_anxiety', 'distraction'], '{}', 'safe', '{"iep": "Alternate testing location to reduce distractions during assessments.", "parent": "Your child may take tests in a quieter space to help them focus."}', ARRAY['IEP/504 Checklist'], 'active'),

('accommodation', 'Frequent Check-Ins for Understanding', 'Staff regularly check the student''s understanding of instructions, expectations, and task requirements.', '["Use neutral prompts (e.g., ''Tell me the first step'')", "Avoid singling out the student in front of peers", "Confirm understanding before independent work"]', ARRAY['communication', 'academics_reading', 'academics_writing', 'academics_math'], ARRAY['adhd', 'autism', 'specific_learning_disability'], ARRAY['preschool', 'elementary', 'middle_school'], ARRAY['general_ed', 'small_group'], ARRAY['comprehension', 'directions'], '{}', 'safe', '{"iep": "Staff will check for understanding throughout instruction and independent work.", "parent": "Teachers may check in to make sure your child understands directions and expectations."}', ARRAY['IEP/504 Checklist'], 'active'),

('accommodation', 'Movement Breaks', 'Planned opportunities for physical movement to support attention and regulation.', '["Build breaks into the routine or offer as-needed within parameters", "Use functional movement options (e.g., delivering a note, stretching, brief walk)"]', ARRAY['sensory_regulation', 'attention_executive_function'], ARRAY['adhd', 'autism'], ARRAY['preschool', 'elementary', 'middle_school'], ARRAY['general_ed', 'special_ed'], ARRAY['regulation', 'attention'], ARRAY['Monitor to ensure breaks do not become escape-maintained patterns'], 'safe', '{"iep": "Planned movement breaks to support attention and engagement.", "parent": "Your child may have short movement breaks to help them stay focused."}', ARRAY['IEP/504 Checklist'], 'active'),

('accommodation', 'Organizational Supports', 'Use of checklists, planners, organizers, or structured routines to support organization and task completion.', '["Provide explicit instruction for how to use the tool", "Review daily or per class period as needed", "Use consistent formats across settings when possible"]', ARRAY['attention_executive_function'], ARRAY['adhd', 'specific_learning_disability', 'anxiety'], ARRAY['elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['organization', 'work_completion'], '{}', 'safe', '{"iep": "Use of organizational tools to support materials management and task completion.", "parent": "Your child may use checklists or planners to stay organized and complete work."}', ARRAY['IEP/504 Checklist'], 'active'),

('accommodation', 'Reduced Visual Distractions', 'The learning environment is arranged to minimize unnecessary visual input and improve focus.', '["Keep workspace clear of unrelated materials", "Limit clutter near seating area", "Use simple visual backgrounds when possible"]', ARRAY['attention_executive_function', 'environmental_access'], ARRAY['adhd', 'autism'], ARRAY['preschool', 'elementary', 'middle_school'], ARRAY['general_ed', 'small_group'], ARRAY['distraction', 'focus'], '{}', 'safe', '{"iep": "Reduction of visual distractions in the learning environment to support attention.", "parent": "Your child''s workspace may be kept simple to help them focus."}', ARRAY['IEP/504 Checklist'], 'active'),

('accommodation', 'Peer Support / Buddy System', 'A peer buddy supports transitions, participation, or organization as appropriate.', '["Rotate peers as appropriate to avoid dependence", "Provide clear roles and expectations", "Use primarily for transitions and unstructured times if needed"]', ARRAY['social_emotional', 'transitions'], ARRAY['autism', 'anxiety', 'adhd'], ARRAY['elementary', 'middle_school'], ARRAY['general_ed', 'lunch_recess'], ARRAY['peer_support', 'transitions'], ARRAY['Avoid reliance on a single peer or creating social imbalance'], 'safe', '{"iep": "Peer support to assist with transitions and participation as appropriate.", "parent": "Your child may have a peer buddy to help during parts of the school day."}', ARRAY['IEP/504 Checklist'], 'active'),

('modification', 'Modified Grading Criteria', 'Evaluation criteria are adjusted based on individualized learning needs and documented IEP goals.', '["Document criteria and rationale in the IEP", "Align grading with modified objectives or alternate standards when applicable", "Ensure team agreement and consistent implementation"]', ARRAY['academics_reading', 'academics_writing', 'academics_math'], ARRAY['intellectual_disability', 'specific_learning_disability'], ARRAY['elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['grading', 'evaluation'], ARRAY['Requires IEP team agreement; impacts standards-based grading'], 'modification', '{"iep": "Grading criteria may be modified in alignment with individualized goals and objectives.", "parent": "Your child''s grading may be adjusted based on their learning plan and goals."}', ARRAY['IEP/504 Checklist'], 'active');