-- Insert batch 02: Sensory, Anxiety, Emotional Regulation & Environment (Items 16-30)
INSERT INTO public.iep_library_items (item_type, title, description, implementation_notes, domains, disability_tags, grade_band, setting_tags, topics, contraindications, idea_compliance_level, export_language, status)
VALUES
  ('accommodation', 'Quiet Space for Regulation', 'Access to a designated quiet space to support emotional or sensory regulation.', '["Establish clear expectations for use", "Limit duration and frequency as appropriate", "Pair with a return-to-task plan"]'::jsonb, ARRAY['sensory_regulation', 'behavior'], ARRAY['autism', 'anxiety', 'adhd'], ARRAY['preschool', 'elementary', 'middle_school'], ARRAY['general_ed', 'special_ed'], ARRAY['regulation', 'overstimulation'], ARRAY['Avoid reinforcing escape-maintained behavior'], 'safe', '{"iep": "Access to a quiet space to support sensory and emotional regulation.", "parent": "Your child may use a quiet area to calm their body when needed."}'::jsonb, 'active'),
  
  ('accommodation', 'Sensory Tools (Fidgets)', 'Access to appropriate sensory tools to support focus and regulation.', '["Select tools that do not distract others", "Teach appropriate use", "Monitor effectiveness"]'::jsonb, ARRAY['sensory_regulation', 'attention_executive_function'], ARRAY['autism', 'adhd'], ARRAY['preschool', 'elementary', 'middle_school'], ARRAY['general_ed', 'small_group'], ARRAY['self_regulation'], ARRAY['Remove if used in a disruptive manner'], 'safe', '{"iep": "Access to sensory tools to support regulation and attention.", "parent": "Your child may use small tools to help their body stay calm and focused."}'::jsonb, 'active'),
  
  ('accommodation', 'Advance Notice of Schedule Changes', 'Student receives advance notice of changes to routines or schedules.', '["Provide verbal and visual notice when possible", "Review changes prior to transitions"]'::jsonb, ARRAY['transitions', 'social_emotional'], ARRAY['autism', 'anxiety'], ARRAY['preschool', 'elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['predictability', 'routine_changes'], ARRAY[]::text[], 'safe', '{"iep": "Advance notice of schedule changes to support transitions.", "parent": "Your child may be told ahead of time if routines will change."}'::jsonb, 'active'),
  
  ('accommodation', 'Calming Strategies Instruction', 'Explicit teaching of calming and coping strategies to support emotional regulation.', '["Teach strategies proactively", "Practice during calm periods", "Prompt use during stress"]'::jsonb, ARRAY['social_emotional', 'behavior'], ARRAY['anxiety', 'autism', 'adhd'], ARRAY['elementary', 'middle_school'], ARRAY['general_ed', 'small_group'], ARRAY['coping_skills', 'emotional_regulation'], ARRAY[]::text[], 'safe', '{"iep": "Instruction in calming strategies to support emotional regulation.", "parent": "Your child may learn ways to calm themselves when feeling overwhelmed."}'::jsonb, 'active'),
  
  ('accommodation', 'Positive Reinforcement System', 'Use of positive reinforcement to increase desired behaviors and engagement.', '["Define target behaviors clearly", "Provide immediate and consistent reinforcement", "Fade gradually as skills improve"]'::jsonb, ARRAY['behavior'], ARRAY['adhd', 'autism', 'emotional_disturbance'], ARRAY['preschool', 'elementary', 'middle_school'], ARRAY['general_ed', 'special_ed'], ARRAY['motivation', 'engagement'], ARRAY['Avoid overreliance on tangible rewards'], 'safe', '{"iep": "Use of positive reinforcement to support appropriate behavior and engagement.", "parent": "Your child may earn positive feedback or rewards for appropriate behaviors."}'::jsonb, 'active'),
  
  ('accommodation', 'Break Card / Cool-Down Pass', 'Student may use a pass to request a brief break when experiencing stress.', '["Limit number of uses per period", "Teach appropriate use", "Include clear return expectations"]'::jsonb, ARRAY['behavior', 'social_emotional'], ARRAY['anxiety', 'autism'], ARRAY['elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['self_advocacy', 'stress_management'], ARRAY['Monitor for task avoidance'], 'safe', '{"iep": "Use of a break pass to request brief breaks as needed.", "parent": "Your child may ask for a short break when feeling overwhelmed."}'::jsonb, 'active'),
  
  ('accommodation', 'Reduced Auditory Distractions', 'Environmental adjustments are made to minimize background noise.', '["Seat away from noise sources", "Use sound-dampening materials when available"]'::jsonb, ARRAY['auditory_access', 'attention_executive_function'], ARRAY['adhd', 'autism', 'deaf_hard_of_hearing'], ARRAY['preschool', 'elementary', 'middle_school'], ARRAY['general_ed'], ARRAY['noise_sensitivity'], ARRAY[]::text[], 'safe', '{"iep": "Reduction of auditory distractions to support attention and access to instruction.", "parent": "The classroom may be arranged to reduce noise that distracts your child."}'::jsonb, 'active'),
  
  ('accommodation', 'Designated Adult Check-In', 'Student has access to a designated adult for emotional support and problem-solving.', '["Schedule regular check-ins", "Use as needed during heightened stress"]'::jsonb, ARRAY['social_emotional', 'behavior'], ARRAY['anxiety', 'emotional_disturbance'], ARRAY['elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['emotional_support'], ARRAY['Avoid dependency without skill-building'], 'safe', '{"iep": "Access to a designated adult for emotional support as needed.", "parent": "Your child may check in with a trusted adult at school for support."}'::jsonb, 'active'),
  
  ('accommodation', 'Flexible Seating Options', 'Student may use alternative seating to support regulation and engagement.', '["Offer options such as wobble stools or cushions", "Monitor impact on learning"]'::jsonb, ARRAY['sensory_regulation', 'attention_executive_function'], ARRAY['adhd', 'autism'], ARRAY['preschool', 'elementary', 'middle_school'], ARRAY['general_ed'], ARRAY['seating', 'regulation'], ARRAY['Remove if distracting to student or peers'], 'safe', '{"iep": "Use of flexible seating options to support attention and regulation.", "parent": "Your child may use different seating to help them focus."}'::jsonb, 'active'),
  
  ('accommodation', 'Visual Coping Cue Cards', 'Visual cues remind the student of coping strategies during stressful situations.', '["Teach meaning of each cue", "Place cards in accessible locations"]'::jsonb, ARRAY['social_emotional', 'communication'], ARRAY['anxiety', 'autism'], ARRAY['elementary', 'middle_school'], ARRAY['general_ed'], ARRAY['coping_skills'], ARRAY[]::text[], 'safe', '{"iep": "Use of visual coping cues to support self-regulation.", "parent": "Your child may use pictures or cards to remember calming strategies."}'::jsonb, 'active'),
  
  ('accommodation', 'Gradual Exposure to Stressful Tasks', 'Tasks that cause anxiety are introduced gradually with support.', '["Start with brief exposure", "Increase duration as tolerance improves"]'::jsonb, ARRAY['social_emotional', 'behavior'], ARRAY['anxiety'], ARRAY['elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['task_avoidance'], ARRAY['Avoid forced participation without support'], 'safe', '{"iep": "Gradual introduction of challenging tasks to reduce anxiety.", "parent": "Your child may work up slowly to harder tasks to reduce stress."}'::jsonb, 'active'),
  
  ('accommodation', 'Structured Daily Routine', 'Consistent daily routines are maintained to support predictability and engagement.', '["Post routines visually", "Review routines regularly"]'::jsonb, ARRAY['transitions', 'attention_executive_function'], ARRAY['autism', 'anxiety'], ARRAY['preschool', 'elementary'], ARRAY['general_ed'], ARRAY['routine'], ARRAY[]::text[], 'safe', '{"iep": "Consistent daily routines to support predictability and engagement.", "parent": "Your child may follow a consistent daily routine at school."}'::jsonb, 'active'),
  
  ('accommodation', 'Emotional Rating Scale', 'Student uses a scale to identify and communicate emotional states.', '["Teach scale meaning", "Use for proactive regulation"]'::jsonb, ARRAY['social_emotional', 'communication'], ARRAY['autism', 'anxiety'], ARRAY['elementary', 'middle_school'], ARRAY['general_ed'], ARRAY['emotional_awareness'], ARRAY[]::text[], 'safe', '{"iep": "Use of an emotional rating scale to support communication and regulation.", "parent": "Your child may use a scale to show how they are feeling."}'::jsonb, 'active'),
  
  ('accommodation', 'Home–School Communication System', 'Regular communication between home and school to support consistency.', '["Use daily or weekly format", "Share strengths and concerns"]'::jsonb, ARRAY['behavior', 'communication'], ARRAY['adhd', 'autism', 'emotional_disturbance'], ARRAY['preschool', 'elementary', 'middle_school'], ARRAY['general_ed'], ARRAY['consistency'], ARRAY['Avoid punitive-only reporting'], 'safe', '{"iep": "Use of a home–school communication system to support consistency.", "parent": "The school may share regular updates with you about your child''s day."}'::jsonb, 'active'),
  
  ('accommodation', 'Preparation for Emergency Drills', 'Student receives preparation and support for emergency and safety drills.', '["Explain drills in advance", "Provide visual or verbal warnings when possible"]'::jsonb, ARRAY['safety', 'social_emotional'], ARRAY['autism', 'anxiety'], ARRAY['preschool', 'elementary', 'middle_school'], ARRAY['general_ed'], ARRAY['safety_drills'], ARRAY[]::text[], 'safe', '{"iep": "Preparation and support for participation in emergency drills.", "parent": "Your child may be prepared ahead of time for school safety drills."}'::jsonb, 'active');