-- Insert batch 06: Health, Safety, Medical, Feeding & Physical Access (Items 76-90)
INSERT INTO public.iep_library_items (item_type, title, description, implementation_notes, domains, disability_tags, grade_band, setting_tags, topics, contraindications, idea_compliance_level, export_language, status)
VALUES
  ('accommodation', 'Health-Related Breaks', 'Student is permitted health-related breaks as needed to support participation and well-being.', '["Define parameters for breaks when possible", "Coordinate with nurse/health plan if applicable"]'::jsonb, ARRAY['health_medical', 'environmental_access'], ARRAY['other_health_impairment', '504_only'], ARRAY['preschool', 'elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['health_support'], ARRAY['Monitor to ensure breaks do not become avoidance-maintained without support'], 'safe', '{"iep": "Health-related breaks permitted as needed to support participation.", "parent": "Your child may take breaks when needed for health reasons."}'::jsonb, 'active'),
  
  ('accommodation', 'Access to School Nurse / Health Office', 'Student may access the nurse or health office when health needs arise.', '["Establish clear procedures", "Notify caregivers per school policy"]'::jsonb, ARRAY['health_medical', 'safety'], ARRAY['other_health_impairment', '504_only'], ARRAY['preschool', 'elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['medical_access'], ARRAY[]::text[], 'safe', '{"iep": "Access to the health office/nurse as needed for health concerns.", "parent": "Your child may go to the nurse if they are not feeling well or need support."}'::jsonb, 'active'),
  
  ('accommodation', 'Medication Administration Plan', 'A plan is in place to support medication administration per school policy.', '["Follow district procedures and documentation", "Ensure confidentiality"]'::jsonb, ARRAY['health_medical', 'safety'], ARRAY['other_health_impairment', '504_only'], ARRAY['preschool', 'elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['medication'], ARRAY[]::text[], 'safe', '{"iep": "Medication administration procedures implemented per school policy.", "parent": "The school will follow a plan for any medications your child needs during the day."}'::jsonb, 'active'),
  
  ('accommodation', 'Safety Plan for High-Risk Behaviors', 'A safety plan is implemented to address specific safety risks (e.g., elopement, aggression, self-injury).', '["Define staff roles and response steps", "Review and practice procedures as needed"]'::jsonb, ARRAY['safety', 'behavior'], ARRAY['autism', 'emotional_disturbance'], ARRAY['preschool', 'elementary', 'middle_school', 'high_school'], ARRAY['general_ed', 'hallways_transitions', 'lunch_recess'], ARRAY['elopement', 'aggression', 'self_injury'], ARRAY['Avoid restrictive practices unless required by policy and team decision'], 'caution', '{"iep": "Implementation of a safety plan to address identified safety risks.", "parent": "The school will follow a safety plan to help keep your child and others safe."}'::jsonb, 'active'),
  
  ('accommodation', 'Adult Escort During Transitions', 'Adult support is provided during transitions to increase safety and success.', '["Identify targeted transitions (e.g., hallway, arrival/dismissal)", "Fade support when appropriate"]'::jsonb, ARRAY['safety', 'transitions'], ARRAY['autism', 'emotional_disturbance', 'adhd'], ARRAY['preschool', 'elementary', 'middle_school'], ARRAY['hallways_transitions'], ARRAY['transition_support'], ARRAY['Avoid unnecessary long-term dependence without plan to build independence'], 'safe', '{"iep": "Adult support during transitions to promote safety and successful routines.", "parent": "An adult may support your child during transitions such as moving between classrooms."}'::jsonb, 'active'),
  
  ('accommodation', 'Emergency Evacuation Support Plan', 'Student receives individualized supports for emergency evacuation procedures.', '["Identify staff responsibilities", "Practice using student-appropriate preparation"]'::jsonb, ARRAY['safety', 'social_emotional'], ARRAY['autism', 'anxiety', 'deaf_hard_of_hearing'], ARRAY['preschool', 'elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['emergency_procedures'], ARRAY[]::text[], 'safe', '{"iep": "Individualized supports for participation in emergency evacuation procedures.", "parent": "Your child will receive extra support during emergency drills if needed."}'::jsonb, 'active'),
  
  ('accommodation', 'Feeding Support Plan', 'A plan is implemented to support safe eating and mealtime routines when needed.', '["Follow medical guidance if applicable", "Train staff on procedures and supervision needs"]'::jsonb, ARRAY['health_medical', 'safety'], ARRAY['autism', 'other_health_impairment'], ARRAY['preschool', 'elementary'], ARRAY['lunch_recess'], ARRAY['feeding', 'choking_risk'], ARRAY['Requires medical collaboration when applicable'], 'caution', '{"iep": "Implementation of a feeding support plan to promote safe mealtime routines.", "parent": "The school will follow a plan to support safe eating during meals."}'::jsonb, 'active'),
  
  ('accommodation', 'Preferential Seating for Safety', 'Student is seated to support safety and appropriate supervision as needed.', '["Seat where supervision is optimal", "Avoid stigmatizing placement"]'::jsonb, ARRAY['safety', 'behavior'], ARRAY['autism', 'emotional_disturbance'], ARRAY['preschool', 'elementary', 'middle_school'], ARRAY['general_ed'], ARRAY['safety_support'], ARRAY[]::text[], 'safe', '{"iep": "Seating arranged to support supervision and safety as needed.", "parent": "Your child may sit where staff can best support their safety."}'::jsonb, 'active'),
  
  ('accommodation', 'Accessible Classroom Pathways', 'Classroom layout ensures clear and accessible pathways for movement and participation.', '["Maintain clear walkways", "Ensure access to instructional areas and materials"]'::jsonb, ARRAY['environmental_access', 'motor_physical'], ARRAY['other_health_impairment', '504_only'], ARRAY['preschool', 'elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['mobility_access'], ARRAY[]::text[], 'safe', '{"iep": "Classroom pathways arranged to ensure accessible movement and participation.", "parent": "The classroom may be arranged to help your child move safely and easily."}'::jsonb, 'active'),
  
  ('accommodation', 'Adaptive Equipment for Physical Tasks', 'Student uses adaptive equipment to access physical activities and classroom tasks.', '["Select equipment based on needs", "Train staff and student in use"]'::jsonb, ARRAY['motor_physical', 'environmental_access'], ARRAY['other_health_impairment', '504_only'], ARRAY['preschool', 'elementary', 'middle_school', 'high_school'], ARRAY['pe', 'general_ed'], ARRAY['adaptive_equipment'], ARRAY[]::text[], 'safe', '{"iep": "Use of adaptive equipment to support access to physical activities and tasks.", "parent": "Your child may use special equipment to participate in activities."}'::jsonb, 'active'),
  
  ('accommodation', 'Adapted PE Equipment', 'Equipment is adjusted (e.g., size, weight, texture) to support participation in PE or motor tasks.', '["Modify size/weight/color as appropriate", "Use auditory signal equipment when helpful"]'::jsonb, ARRAY['motor_physical', 'environmental_access'], ARRAY['other_health_impairment', 'autism', 'deaf_hard_of_hearing'], ARRAY['preschool', 'elementary', 'middle_school'], ARRAY['pe'], ARRAY['pe_access', 'equipment_adaptation'], ARRAY[]::text[], 'safe', '{"iep": "Adapted equipment provided to support participation in physical education activities.", "parent": "Your child may use adjusted equipment in PE so they can participate successfully."}'::jsonb, 'active'),
  
  ('accommodation', 'Environmental Sensory Adjustments (Light/Sound)', 'Adjustments are made to sensory input such as lighting or sound to support participation.', '["Use seating placement and environmental aids", "Offer noise-reducing supports if appropriate"]'::jsonb, ARRAY['sensory_regulation', 'environmental_access'], ARRAY['autism', 'anxiety', 'deaf_hard_of_hearing'], ARRAY['preschool', 'elementary', 'middle_school', 'high_school'], ARRAY['general_ed'], ARRAY['sensory_sensitivity'], ARRAY[]::text[], 'safe', '{"iep": "Environmental sensory adjustments implemented to support regulation and access.", "parent": "The classroom environment may be adjusted to reduce sensory overwhelm."}'::jsonb, 'active'),
  
  ('accommodation', 'Extra Time for Movement Between Classes', 'Student is provided additional time to move between locations to support safe and successful transitions.', '["Apply for specific transitions as needed", "Coordinate with schedule and staff support"]'::jsonb, ARRAY['transitions', 'motor_physical'], ARRAY['other_health_impairment', '504_only'], ARRAY['middle_school', 'high_school'], ARRAY['hallways_transitions'], ARRAY['mobility', 'transition_support'], ARRAY[]::text[], 'safe', '{"iep": "Additional time provided for movement between classes as needed.", "parent": "Your child may have extra time to get to class safely."}'::jsonb, 'active'),
  
  ('accommodation', 'Preferential Locker Location', 'Locker location is assigned to reduce travel demands and support organization.', '["Assign near classrooms or accessible areas", "Coordinate with supervision needs"]'::jsonb, ARRAY['environmental_access', 'attention_executive_function'], ARRAY['other_health_impairment', 'adhd', '504_only'], ARRAY['middle_school', 'high_school'], ARRAY['general_ed', 'hallways_transitions'], ARRAY['organization', 'mobility'], ARRAY[]::text[], 'safe', '{"iep": "Preferential locker location to support accessibility and organization.", "parent": "Your child''s locker may be placed in a location that is easier to access."}'::jsonb, 'active'),
  
  ('modification', 'Modified PE Rules or Objectives', 'Rules, objectives, or expectations in PE are modified to support participation and safety.', '["Align modifications to individualized needs", "Maintain participation goals whenever possible"]'::jsonb, ARRAY['motor_physical'], ARRAY['other_health_impairment', 'intellectual_disability'], ARRAY['preschool', 'elementary', 'middle_school'], ARRAY['pe'], ARRAY['pe_modification'], ARRAY['Requires team agreement when altering standards or grading'], 'modification', '{"iep": "PE rules or objectives may be modified to support safe participation.", "parent": "Your child''s PE expectations may be adjusted so they can participate safely."}'::jsonb, 'active');